[package]
name                   = "nh-installable"
description            = "This is an internal component crate of nh"
version.workspace      = true
publish                = true
edition.workspace      = true
license = "EUPL-1.2"
rust-version.workspace = true

[dependencies]
clap.workspace       = true
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
tracing.workspace    = true
yansi = "1.0.1"

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
