[package]
name = "derputils"
version = "24.1.0"
description = """\
    A set of utils which deserve questioning \
    what's purpose of their existence in the first place.\
    """
license = "MIT"
authors.workspace = true
edition.workspace = true
repository.workspace = true

# Dependencies

[dependencies]
anyhow.workspace = true
argh = "0.1"
directories = "5.0.1"
itertools = "0.12.0"
once_cell = "1"
qrcode-generator = "4.1"
rand = "0.8"
sdl2 = "0.36"
tracing.workspace = true
tracing-subscriber.workspace = true
