[package]
name = "derputils"
version = "4.2.0"
description = """\
    A set of utils which deserve questioning \
    what's purpose of their existence in the first place.\
    """
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

# Dependencies

[dependencies]
anyhow.workspace = true
argh.workspace = true
ino_tracing.workspace = true
itertools = "0.12.0"
once_cell = "1"
qrcode-generator = { version = "4.1", default-features = false }
sdl2 = "0.36"
tracing.workspace = true
