[package]
name = "derputils"
version = "9.0.0"
description = """\
    A set of utils which deserve questioning \
    what's purpose of their existence in the first place.\
    """
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
ino_shell.workspace = true
ino_color.workspace = true
ino_path.workspace = true
bpaf.workspace = true
ino_tracing.workspace = true
qrcode = { version = "0", features = ["svg"] }
rootcause.workspace = true
tracing.workspace = true
uuid = { version = "1", features = ["v7"] }
gix-discover = { version = "0.55.0", features = [ "sha1" ] }
path-clean.workspace = true

[dev-dependencies]
assert_fs.workspace = true

[lints]
workspace = true
