[package]
name = "ino_shell"
description = "Utilities for quick shell scripting in Rust (fork of xshell)"
categories = ["development-tools::build-utils", "filesystem"]
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MidAutumnMoon/InOri"
authors = [
    "Alex Kladov <aleksey.kladov@gmail.com>",
    "MidAutumnMoon"
]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ino_shell-macros = { path = "./ino_shell-macros", version = "1" }

[dev-dependencies]
rootcause.workspace = true

[[bin]]
name = "xecho"
path = "bin/xecho.rs"

[[bin]]
name = "xsleep"
path = "bin/xsleep.rs"
