[package]
name = "ino_shell"
description = "Utilities for quick shell scripting in Rust"
categories = ["development-tools::build-utils", "filesystem"]
version = "0.3.0-pre.2" # also update ino_shell-macros/Cargo.toml and CHANGELOG.md
license = "MIT OR Apache-2.0"
repository = "https://github.com/matklad/xshell"
authors = ["Alex Kladov <aleksey.kladov@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ino_shell-macros = { path = "./ino_shell-macros" }

[dev-dependencies]
anyhow.workspace = true
