[package]
name                   = "nh-core"
description            = "This is an internal component crate of nh"
version.workspace      = true
edition.workspace      = true
license = "EUPL-1.2"
rust-version.workspace = true
publish                = true

[dependencies]
clap.workspace           = true
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
indicatif.workspace      = true
inquire = { default-features = false, features = [ "crossterm" ], version = "0.9.1" }
nh-installable = { path = "../nh-installable" }
nix = { default-features = false, features = [ "fs", "user", "hostname" ], version = "0.31.1" }
nix-command = { path = "../nix-command" }
regex = "1.12.2"
secrecy = { features = [ "serde" ], version = "0.10.3" }
semver = "1.0.27"
serde_json.workspace     = true
shlex = "2.0.1"
subprocess = "1.0.3"
thiserror.workspace      = true
tracing.workspace        = true
which = "8.0.0"

[dev-dependencies]
proptest = "1.9.0"
serial_test = "3.2.0"
tempfile = "3.23.0"


[lints]
workspace = true
