[workspace]
resolver = "2"
members = [
    "crates/*",
    "avxl",
    "coruma",
    "derputils",
    "rpgdemake",
]

[workspace.package]
authors = [ "MidAutumnMoon" ]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/MidAutumnMoon/InOri"
rust-version = "1.83.0"


#
# Dependencies
#

[workspace.dependencies]
anyhow = { version = "1", features = [ "backtrace" ] }
clap = { version = "4", features = [ "derive", "cargo", "wrap_help" ] }
itertools = "0"
rayon = "1"
tap = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

ino_color = { path = "./crates/ino_color" }
ino_tracing = { path = "./crates/ino_tracing" }
ino_path = { path = "./crates/ino_path" }


#
# Profiles
#

[profile.release]
lto = "thin"
strip = "debuginfo"

[profile.perf]
inherits = "release"
debug = true
strip = false
