[workspace]
resolver = "3"
members = [
    "crates/*",
    "./crates/ino_shell/ino_shell-macros",
    "coruma",
    "derputils",
    "lny",
    "rpgdemake",
    "imgo",
    "./noah",
    "./noah/crates/*",
]

[workspace.package]
authors = [ "MidAutumnMoon" ]
license = "GPL-3.0-or-later"
repository = "https://github.com/MidAutumnMoon/InOri"
edition = "2024"
rust-version = "1.98.0"
version = "5.0.0"
homepage = "https://github.com/nix-community/nh"

#
# Dependencies
#

[workspace.dependencies]
# InOri internal crates
ino_color = { path = "./crates/ino_color" }
ino_tracing = { path = "./crates/ino_tracing" }
ino_path = { path = "./crates/ino_path" }
ino_shell = { path = "./crates/ino_shell" }

# Shared dependencies (InOri + Noah)
anyhow = "1"
assert_fs = "1"
bpaf = { version = "0.9", features = [ "dull-color", "autocomplete" ] }
clap = { version = "4", features = [ "cargo", "color", "derive", "env", "unstable-styles" ] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif", "bmp"] }
indicatif = "0.18"
itertools = "0"
rayon = "1"
rootcause = "0"
rustix = { version = "1", features = [ "all-apis" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
strum = { version = "0", features = ["derive"] }
tap = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "registry", "std" ] }

#
# Profiles
#

[profile.release]
lto = "thin"
strip = "debuginfo"

[profile.perf]
inherits = "release"
debug = true
strip = false

#
# Lints
#

[workspace.lints.clippy]
all = { priority = -1, level = "warn" }
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -1, level = "warn" }
correctness = { level = "deny", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
restriction = { level = "warn", priority = -1 }

cognitive_complexity = "allow"
missing_const_for_fn = "allow" # has bug
too_many_lines = "allow"

# Noah allows
struct_excessive_bools = "allow"

# Allow quite few lints from correctness group
implicit_return = "allow"
default_numeric_fallback = "allow"
question_mark_used = "allow"
shadow_same = "allow"
shadow_reuse = "allow"
print_stderr = "allow"
print_stdout = "allow"
