[workspace]
resolver = "2"
members = [
    "crates/*",
    "avxl",
    "derputils",
    "rpgdemake",
]


[workspace.package]
authors = [ "MidAutumnMoon" ]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/MidAutumnMoon/InOri"
rust-version = "1.80.0"


#
# Dependencies
#

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = [ "derive", "cargo", "wrap_help" ] }
mimalloc = "0.1"
rayon = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

# Homemade crates
ino_tracing = { path = "./crates/ino_tracing" }

#
# Profiles
#

[profile.release]
lto = "thin"
strip = "debuginfo"

[profile.perf]
inherits = "release"
debug = true
strip = false
