[workspace]
resolver = "2"
members = [
    "derputils",
]


[workspace.package]
authors = [ "MidAutumnMoon" ]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/MidAutumnMoon/TeapotInOri"


[workspace.dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter"
] }


[profile.release]
lto = "thin"
strip = "debuginfo"
