[workspace]
resolver = "2"
members = [
    "libs/*",
    "derputils",
    "latoori", "rpgdemake",
]


[workspace.package]
authors = [ "MidAutumnMoon" ]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/MidAutumnMoon/TeapotInOri"


#
# Dependencies
#

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = [ "derive", "cargo" ] }
colored = "2"
mimalloc = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

# Homemade crates
ino_tracing = { path = "./libs/ino_tracing" }

[workspace.dependencies."tokio"]
version = "1"
features = [
    "fs",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
]


#
# Profiles
#

[profile.release]
lto = "thin"
strip = "debuginfo"
