[workspace]
resolver = "2"
members = [
    "derputils",
    "libs/*",
]


[workspace.package]
authors = [ "MidAutumnMoon" ]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/MidAutumnMoon/TeapotInOri"


[workspace.dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter"
] }
# Homemade crates
ino_tracing = { path = "./libs/ino_tracing" }


[profile.release]
lto = "thin"
strip = "debuginfo"
