[package]
name                   = "nix-command"
description            = "Nix command builder backed by subprocess execution"
version                = "0.3.0"
edition.workspace      = true
rust-version.workspace = true
license = "EUPL-1.2"
homepage.workspace     = true
publish                = true

[dependencies]
subprocess = "1.2.1"
thiserror.workspace  = true

[lints]
workspace = true
