[package]
name                   = "nh"
license = "EUPL-1.2"
repository             = "https://github.com/nix-community/nh"
description            = "Yet Another Nix Helper"
keywords               = [ "nix", "nixos", "nix-darwin", "helper", "CLI" ]
readme                 = "../../docs/README.md"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
default-run            = "nh"

[dependencies]
anstyle = "1.0.13"
clap.workspace                = true
clap-verbosity-flag = { default-features = false, features = [ "tracing" ], version = "3.0.4" }
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
nh-clean = { path = "../nh-clean" }
nh-core = { path = "../nh-core" }
nh-nixos = { path = "../nh-nixos" }
nh-search = { path = "../nh-search" }
tracing.workspace             = true
tracing-subscriber.workspace  = true
yansi = "1.0.1"

[dev-dependencies]
serial_test = "3.2.0"

[lints]
workspace = true
