[package]
name                   = "nh-diff"
description            = "This is an internal component crate of nh"
version.workspace      = true
publish                = true
edition.workspace      = true
license = "EUPL-1.2"
rust-version.workspace = true

[dependencies]
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
dix = "2.1.0"
nh-core = { path = "../nh-core" }
nh-remote = { path = "../nh-remote" }
tracing.workspace    = true
yansi = "1.0.1"

[lints]
workspace = true
