[package]
name = "avxl"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ino_tracing.workspace = true
itertools.workspace = true
tracing.workspace = true
