use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::io::Write as _;
use std::num::NonZeroU64;
use std::path::Component;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;
use std::time::UNIX_EPOCH;

use bpaf::Parser;
use bpaf::construct;
use bpaf::long;
use bpaf::positional;
use indicatif::ProgressBar;
use indicatif::ProgressStyle;
use rayon::ThreadPoolBuilder;
use rayon::prelude::*;
use rootcause::bail;
use rootcause::option_ext::OptionExt as _;
use rootcause::prelude::ResultExt as _;
use serde::Deserialize;
use serde::Serialize;
use tempfile::Builder;

use crate::BACKUP_DIR_NAME;
use crate::REVIEW_DIR_NAME;
use crate::classify::AnalyzedImage;
use crate::classify::ContentClass;
use crate::classify::GroupKey;
use crate::classify::ImageFeatures;
use crate::classify::SandToneBurden;
use crate::classify::ScaleClass;
use crate::classify::analyze;
use crate::fs::backup_path;
use crate::fs::collect_images;
use crate::img::Image;
use crate::img::ImageFormat;
use crate::pipeline::Job;
use crate::pipeline::run_jobs;
use crate::recipe::Recipe;
use crate::recipe::Step;
use crate::transcoder::Tool;
use crate::transcoder::avif::Avif;
use crate::transcoder::avif::Chroma;
use crate::transcoder::jxl::Jxl;
use crate::transcoder::magick::CleanScan;
use crate::transcoder::magick::Denoise;
use crate::transcoder::magick::FlattenSandTone;
use crate::transcoder::magick::Mode;
use crate::transcoder::magick::SandToneStrength;

const PLAN_VERSION: u32 = 5;
const DEFAULT_PLAN_NAME: &str = "imgo-plan.json";
const REVIEW_VERSION: u32 = 4;
const REVIEW_MANIFEST_NAME: &str = ".imgo-review.json";

const SMALL_AVIF_QUALITY: u8 = 68;
const MEDIUM_AVIF_QUALITY: u8 = 65;
const LARGE_AVIF_QUALITY: u8 = 55;
const COMPACT_QUALITY_DELTA: u8 = 7;
const NEAR_BILEVEL_REVIEW_PERCENT: f64 = 68.0;
const PENCIL_MAX_NEAR_BW_PERCENT: f64 = 40.0;
const PENCIL_MIN_GRAY_ENTROPY: f64 = 5.5;
const PENCIL_MIN_SOFT_NOISE_PERCENT: f64 = 8.0;
const SAND_TONE_AVIF_SPEED: u8 = 2;
const REGIONAL_SAND_TONE_LIGHT_MAX_MICROTEXTURE_PERCENT: f64 = 35.0;
const REGIONAL_SAND_TONE_MEDIUM_MAX_MICROTEXTURE_PERCENT: f64 = 50.0;

#[derive(Debug)]
pub struct PlanOpts {
    /// Directory containing source PNG/JPEG images.
    pub workspace: PathBuf,

    /// JSON plan path. Defaults to `<workspace>/imgo-plan.json`.
    pub output: Option<PathBuf>,

    /// Review directory. Defaults to `<workspace>/.imgo-review`.
    pub review_output: Option<PathBuf>,

    /// Analyze only immediate children of the workspace.
    pub no_recursive: bool,

    /// Number of images decoded concurrently (default: at most four).
    pub jobs: Option<NonZeroU64>,

    /// Replace an existing plan and force fresh candidate encodes.
    pub force: bool,
}

/// CLI parser for [`PlanOpts`].
#[must_use]
pub fn plan_cli() -> impl Parser<PlanOpts> {
    let output = long("output")
        .short('o')
        .argument::<PathBuf>("PATH")
        .help("JSON plan path. Defaults to `<workspace>/imgo-plan.json`")
        .optional();
    let review_output = long("review-output")
        .argument::<PathBuf>("DIR")
        .help("Review directory. Defaults to `<workspace>/.imgo-review`")
        .optional();
    let no_recursive = long("no-recursive")
        .short('R')
        .switch()
        .help("Analyze only immediate children of the workspace");
    let jobs = long("jobs")
        .short('J')
        .argument::<NonZeroU64>("N")
        .help("Number of images decoded concurrently (default: at most four)")
        .optional();
    let force = long("force").switch().help(
        "Replace an existing plan and force fresh candidate encodes",
    );
    let workspace = positional::<PathBuf>("WORKSPACE")
        .help("Directory containing source PNG/JPEG images")
        .fallback(PathBuf::from("."));
    construct!(PlanOpts {
        output,
        review_output,
        no_recursive,
        jobs,
        force,
        workspace,
    })
}

#[derive(Debug)]
pub struct RunOpts {
    /// Reviewed plan generated by `i plan`.
    pub plan: PathBuf,

    /// Number of images processed concurrently. Defaults to one because
    /// avifenc/cjxl use all cores internally.
    pub jobs: Option<NonZeroU64>,

    /// Keep originals in place. The default moves them into `.backup` and
    /// enables reliable resume detection.
    pub no_backup: bool,
}

/// CLI parser for [`RunOpts`].
#[must_use]
pub fn run_cli() -> impl Parser<RunOpts> {
    let jobs = long("jobs")
        .short('J')
        .argument::<NonZeroU64>("N")
        .help(
            "Number of images processed concurrently. Defaults to one \
             because avifenc/cjxl use all cores internally",
        )
        .optional();
    let no_backup = long("no-backup").short('N').switch().help(
        "Keep originals in place. The default moves them into \
             `.backup` and enables reliable resume detection",
    );
    let plan = positional::<PathBuf>("PLAN")
        .help("Reviewed plan generated by `i plan`");
    construct!(RunOpts {
        jobs,
        no_backup,
        plan,
    })
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
    version: u32,
    workspace: PathBuf,
    #[serde(default)]
    review_directory: PathBuf,
    groups: Vec<PlanGroup>,
    recipes: BTreeMap<String, Recipe>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct PlanGroup {
    id: String,
    selected_recipe: String,
    candidate_recipes: Vec<String>,
    review_required: bool,
    reasons: Vec<String>,
    metrics: GroupMetrics,
    representative: PathBuf,
    files: Vec<PlannedFile>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct PlannedFile {
    path: PathBuf,
    bytes: u64,
    modified_unix_seconds: u64,
    modified_subsec_nanos: u32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct GroupMetrics {
    color_percent: f64,
    gray_entropy: f64,
    near_bw_percent: f64,
    detail_percent: f64,
    soft_noise_percent: f64,
    max_tile_soft_noise_percent: f64,
    microtexture_percent: f64,
    texture_directional_coherence: f64,
    #[serde(default)]
    sand_tone_region_percent: f64,
    #[serde(default)]
    sand_tone_region_microtexture_percent: f64,
    #[serde(default)]
    threshold_stability_percent: f64,
    #[serde(default)]
    binary_error_mean: f64,
    #[serde(default)]
    smooth_midtone_percent: f64,
    min_longest_edge: u32,
    max_longest_edge: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct ReviewedCandidate {
    source: PlannedFile,
    recipe_name: String,
    recipe: Recipe,
    artifact: PathBuf,
    output_extension: String,
    encoded_modified_unix_seconds: u64,
    encoded_modified_subsec_nanos: u32,
    encoded_bytes: u64,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct ReviewManifest {
    version: u32,
    workspace: PathBuf,
    candidates: Vec<ReviewedCandidate>,
}

/// Phase 1: analyze sources in parallel, encode representative candidates,
/// write the managed review bundle, and persist the editable plan.
///
/// # Errors
///
/// Returns an error for invalid paths, image decode or candidate encode
/// failures, unsafe/existing managed outputs, or serialization errors.
pub fn create_plan(options: &PlanOpts) -> rootcause::Result<PathBuf> {
    let workspace =
        options.workspace.canonicalize().context_with(|| {
            format!("resolve workspace {}", options.workspace.display())
        })?;
    if !workspace.is_dir() {
        bail!("workspace is not a directory");
    }
    let output = options
        .output
        .clone()
        .unwrap_or_else(|| workspace.join(DEFAULT_PLAN_NAME));
    let review_directory = resolve_output_path(
        &options
            .review_output
            .clone()
            .unwrap_or_else(|| workspace.join(REVIEW_DIR_NAME)),
    )?;
    if !options.force && output.exists() {
        bail!(
            "plan already exists: {} (pass --force to replace it)",
            output.display()
        );
    }
    if resolve_output_path(&output)?.starts_with(&review_directory) {
        bail!("plan output cannot be inside its managed review directory");
    }
    validate_review_target(&review_directory, &workspace, options.force)?;
    let previous_manifest = if options.force || !review_directory.exists()
    {
        None
    } else {
        Some(read_review_manifest(&review_directory)?)
    };
    let previous = previous_manifest
        .as_ref()
        .map(|manifest| (manifest, review_directory.as_path()));

    let images = collect_images(
        &workspace,
        &[ImageFormat::PNG, ImageFormat::JPG],
        !options.no_recursive,
    )?;
    if images.is_empty() {
        bail!("no PNG/JPEG images found");
    }
    let analysis_jobs = options.jobs.unwrap_or_else(default_analysis_jobs);
    let progress = analysis_progress(images.len(), analysis_jobs)?;
    let pool = ThreadPoolBuilder::new()
        .num_threads(usize::try_from(analysis_jobs.get())?)
        .build()
        .context("build classifier worker pool")?;
    let results = pool.install(|| {
        images
            .into_par_iter()
            .map(|image| {
                let result = analyze(image);
                progress.inc(1);
                result
            })
            .collect::<Vec<_>>()
    });
    progress.finish_and_clear();
    let analysis =
        results.into_iter().collect::<rootcause::Result<Vec<_>>>()?;

    let plan = Plan::from_analysis(
        workspace,
        review_directory.clone(),
        analysis,
    )?;
    plan.validate()?;
    for tool in collect_required_review_tools(&plan, previous)? {
        tool.verify()?;
    }

    let parent =
        review_directory.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent).context_with(|| {
        format!("create review parent {}", parent.display())
    })?;
    let staging = Builder::new()
        .prefix(".imgo-review-next-")
        .tempdir_in(parent)
        .context("create staged review directory")?;
    let manifest = render_review(&plan, staging.path(), previous)?;
    write_json_atomic(
        &manifest,
        &staging.path().join(REVIEW_MANIFEST_NAME),
    )?;

    let staged_path = staging.keep();
    if review_directory.exists() {
        std::fs::remove_dir_all(&review_directory).context_with(|| {
            format!(
                "replace managed review directory {}",
                review_directory.display()
            )
        })?;
    }
    std::fs::rename(&staged_path, &review_directory).context_with(
        || {
            format!(
                "install staged review {} at {}",
                staged_path.display(),
                review_directory.display()
            )
        },
    )?;

    plan.write(&output, options.force)?;
    print_plan_summary(&plan, &output);
    println!("Review output: {}", review_directory.display());
    println!(
        "Review encoded candidates, edit selected_recipe in {}, then run: i run {}",
        output.display(),
        output.display()
    );
    Ok(output)
}

/// Execute all selected recipes in a validated plan.
///
/// # Errors
///
/// Returns an error when the plan is invalid or stale, preflight detects a
/// conflict, a tool is missing, or one or more image jobs fail.
pub fn run_plan(options: &RunOpts) -> rootcause::Result<()> {
    let plan = Plan::read(&options.plan)?;
    plan.validate()?;
    plan.validate_source_metadata()?;
    let review_manifest =
        read_review_manifest(&plan.review_directory).ok();

    let mut selected_recipes: BTreeMap<String, Arc<Recipe>> =
        BTreeMap::new();
    for group in &plan.groups {
        match selected_recipes.entry(group.selected_recipe.clone()) {
            std::collections::btree_map::Entry::Vacant(entry) => {
                let recipe =
                    plan.recipes.get(entry.key()).context_with(|| {
                        format!("unknown recipe {}", entry.key())
                    })?;
                entry.insert(Arc::new(recipe.clone()));
            }
            std::collections::btree_map::Entry::Occupied(_) => {}
        }
    }
    let mut jobs = Vec::new();
    for group in &plan.groups {
        let recipe = Arc::clone(
            selected_recipes
                .get(&group.selected_recipe)
                .context("selected recipe was not prepared")?,
        );
        for file in &group.files {
            let path = plan.workspace.join(&file.path);
            let format = ImageFormat::from_path(&file.path)
                .context("planned image has unsupported extension")?;
            let reviewed_output = if file.path == group.representative {
                if let Some(manifest) = &review_manifest {
                    reviewed_candidate(
                        manifest,
                        &plan.review_directory,
                        file,
                        format,
                        &group.selected_recipe,
                        &recipe,
                    )?
                } else {
                    None
                }
            } else {
                None
            };
            jobs.push(Job {
                image: Image { path, format },
                recipe: Arc::clone(&recipe),
                reviewed_output,
            });
        }
    }

    let summary = run_jobs(
        &plan.workspace,
        jobs,
        options.no_backup,
        options.jobs.unwrap_or(NonZeroU64::MIN),
    )?;
    println!(
        "Processed {}, already complete {}.",
        summary.processed, summary.already_complete
    );
    Ok(())
}

fn validate_review_target(
    output: &Path,
    workspace: &Path,
    force: bool,
) -> rootcause::Result<()> {
    let resolved_output = resolve_output_path(output)?;
    if resolved_output == workspace
        || workspace.starts_with(&resolved_output)
        || resolved_output.starts_with(workspace.join(BACKUP_DIR_NAME))
    {
        bail!(
            "refusing to manage unsafe review directory {}",
            resolved_output.display()
        );
    }
    if !output.exists() {
        return Ok(());
    }
    if !output.is_dir() {
        bail!("review output is not a directory: {}", output.display());
    }
    if force {
        return Ok(());
    }
    let manifest = read_review_manifest(output).context_with(|| {
        format!(
            "{} is not a managed imgo review directory; pass --force to replace it",
            output.display()
        )
    })?;
    if manifest.version != REVIEW_VERSION
        || manifest.workspace != workspace
    {
        bail!(
            "review directory {} belongs to another schema or workspace; pass --force to replace it",
            output.display()
        );
    }
    Ok(())
}

fn resolve_output_path(path: &Path) -> rootcause::Result<PathBuf> {
    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()?.join(path)
    };
    let mut normalized = PathBuf::new();
    for component in absolute.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            Component::Prefix(_)
            | Component::RootDir
            | Component::Normal(_) => {
                normalized.push(component.as_os_str());
            }
        }
    }
    if normalized.exists() {
        Ok(normalized.canonicalize().context_with(|| {
            format!("resolve review output {}", normalized.display())
        })?)
    } else {
        Ok(normalized)
    }
}

fn read_review_manifest(root: &Path) -> rootcause::Result<ReviewManifest> {
    let path = root.join(REVIEW_MANIFEST_NAME);
    let raw = std::fs::read_to_string(&path).context_with(|| {
        format!("read review manifest {}", path.display())
    })?;
    let manifest = serde_json::from_str(&raw).context_with(|| {
        format!("parse review manifest {}", path.display())
    })?;
    Ok(manifest)
}

fn reviewed_candidate(
    manifest: &ReviewManifest,
    root: &Path,
    planned: &PlannedFile,
    input_format: ImageFormat,
    recipe_name: &str,
    recipe: &Recipe,
) -> rootcause::Result<Option<PathBuf>> {
    if manifest.version != REVIEW_VERSION {
        return Ok(None);
    }
    let output_format = recipe.validate_for(input_format)?;
    let extension = output_format
        .primary_extension()
        .context("recipe output has no extension")?;
    let Some(candidate) = manifest.candidates.iter().find(|candidate| {
        candidate.source.path == planned.path
            && candidate.recipe_name == recipe_name
    }) else {
        return Ok(None);
    };
    if &candidate.source != planned
        || &candidate.recipe != recipe
        || candidate.output_extension != extension
        || candidate.encoded_bytes == 0
    {
        return Ok(None);
    }
    validate_relative_path(&candidate.artifact)?;
    let artifact = root.join(&candidate.artifact);
    let Ok(metadata) = std::fs::metadata(&artifact) else {
        return Ok(None);
    };
    if !metadata.is_file() || metadata.len() != candidate.encoded_bytes {
        return Ok(None);
    }
    let Ok(modified) = metadata.modified() else {
        return Ok(None);
    };
    let Ok(modified) = modified.duration_since(UNIX_EPOCH) else {
        return Ok(None);
    };
    if modified.as_secs() != candidate.encoded_modified_unix_seconds
        || modified.subsec_nanos()
            != candidate.encoded_modified_subsec_nanos
    {
        return Ok(None);
    }
    Ok(Some(artifact))
}

fn collect_required_review_tools(
    plan: &Plan,
    previous: Option<(&ReviewManifest, &Path)>,
) -> rootcause::Result<BTreeSet<Tool>> {
    let mut tools = BTreeSet::new();
    for group in &plan.groups {
        let planned = group
            .files
            .iter()
            .find(|file| file.path == group.representative)
            .context("representative is absent from its group")?;
        let input_format = ImageFormat::from_path(&planned.path)
            .context("planned image has unsupported extension")?;
        for name in group.recipe_names() {
            let recipe = plan
                .recipes
                .get(name)
                .context_with(|| format!("unknown recipe {name}"))?;
            let reused = if let Some((manifest, root)) = previous {
                reviewed_candidate(
                    manifest,
                    root,
                    planned,
                    input_format,
                    name,
                    recipe,
                )?
                .is_some()
            } else {
                false
            };
            if !reused {
                recipe.required_tools(&mut tools);
            }
        }
    }
    Ok(tools)
}

fn render_review(
    plan: &Plan,
    output: &Path,
    previous: Option<(&ReviewManifest, &Path)>,
) -> rootcause::Result<ReviewManifest> {
    let mut candidates = Vec::new();
    for (group_index, group) in plan.groups.iter().enumerate() {
        let planned = group
            .files
            .iter()
            .find(|file| file.path == group.representative)
            .context("representative is absent from its group")?;
        let source = plan.resolve_planned_source(planned)?;
        let input_format = ImageFormat::from_path(&planned.path)
            .context("planned image has unsupported extension")?;
        let directory_name =
            review_group_directory_name(group_index, group, planned);
        let directory = output.join(&directory_name);
        std::fs::create_dir_all(&directory)?;

        let original_file_name = planned
            .path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("image");
        let original_name = format!("00-original--{original_file_name}");
        std::fs::copy(&source, directory.join(&original_name))?;

        let mut report = String::new();
        writeln!(&mut report, "source: {}", planned.path.display())?;
        writeln!(&mut report, "group: {}", group.id)?;
        writeln!(
            &mut report,
            "selected_recipe: {}",
            group.selected_recipe
        )?;
        writeln!(&mut report)?;
        writeln!(&mut report, "{original_name}: original")?;

        println!("\n{} — {}", group.id, planned.path.display());
        for (candidate_index, name) in group.recipe_names().enumerate() {
            let recipe = plan
                .recipes
                .get(name)
                .context_with(|| format!("unknown recipe {name}"))?;
            let output_format = recipe.validate_for(input_format)?;
            let extension = output_format
                .primary_extension()
                .context("recipe output has no extension")?;
            let selected = name == &group.selected_recipe;
            let artifact_name = candidate_artifact_file_name(
                candidate_index + 1,
                name,
                extension,
            );
            let artifact_path = directory.join(&artifact_name);

            let previous_artifact =
                if let Some((manifest, root)) = previous {
                    reviewed_candidate(
                        manifest,
                        root,
                        planned,
                        input_format,
                        name,
                        recipe,
                    )?
                } else {
                    None
                };
            let reused = if let Some(previous_artifact) = previous_artifact
            {
                std::fs::copy(previous_artifact, &artifact_path)?;
                true
            } else {
                let temporary = Builder::new()
                    .prefix(".candidate-")
                    .suffix(&format!(".{extension}"))
                    .tempfile_in(&directory)?;
                recipe.execute(&source, input_format, temporary.path())?;
                if std::fs::metadata(temporary.path())?.len() == 0 {
                    bail!(
                        "candidate recipe {name} produced an empty output"
                    );
                }
                temporary
                    .persist(&artifact_path)
                    .map_err(|error| error.error)
                    .context_with(|| {
                        format!(
                            "commit reviewed candidate {}",
                            artifact_path.display()
                        )
                    })?;
                false
            };

            let metadata = std::fs::metadata(&artifact_path)?;
            let modified =
                metadata.modified()?.duration_since(UNIX_EPOCH)?;
            let artifact =
                PathBuf::from(&directory_name).join(&artifact_name);
            candidates.push(ReviewedCandidate {
                source: planned.clone(),
                recipe_name: name.clone(),
                recipe: recipe.clone(),
                artifact,
                output_extension: extension.to_owned(),
                encoded_modified_unix_seconds: modified.as_secs(),
                encoded_modified_subsec_nanos: modified.subsec_nanos(),
                encoded_bytes: metadata.len(),
            });

            let ratio = size_percent(metadata.len(), planned.bytes);
            let role = if selected { "selected" } else { "candidate" };
            let state = if reused { "reused" } else { "encoded" };
            println!(
                "  {role:9} {name:34} {:>10} bytes ({ratio:5.1}%, {state})",
                metadata.len()
            );
            writeln!(
                &mut report,
                "{artifact_name}: {role}, recipe={name}, encoded_bytes={}, source_percent={ratio:.1}",
                metadata.len()
            )?;
        }
        std::fs::write(directory.join("review.txt"), report)?;
    }
    Ok(ReviewManifest {
        version: REVIEW_VERSION,
        workspace: plan.workspace.clone(),
        candidates,
    })
}

fn review_group_directory_name(
    index: usize,
    group: &PlanGroup,
    representative: &PlannedFile,
) -> String {
    let stem = representative
        .path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("image");
    format!("{:03}--{}--{stem}", index + 1, group.id)
}

fn candidate_artifact_file_name(
    index: usize,
    recipe: &str,
    extension: &str,
) -> String {
    format!("{index:02}--{recipe}.{extension}")
}

fn write_json_atomic<T>(value: &T, path: &Path) -> rootcause::Result<()>
where
    T: Serialize,
{
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent)?;
    let mut temporary =
        Builder::new().prefix(".imgo-json-").tempfile_in(parent)?;
    serde_json::to_writer_pretty(temporary.as_file_mut(), value)?;
    writeln!(temporary.as_file_mut())?;
    temporary.as_file().sync_all()?;
    temporary
        .persist(path)
        .map_err(|error| error.error)
        .context_with(|| format!("commit JSON {}", path.display()))?;
    Ok(())
}

#[expect(
    clippy::cast_precision_loss,
    reason = "ratio is display-only and image file sizes are below f64's exact integer range"
)]
fn size_percent(encoded: u64, source: u64) -> f64 {
    encoded as f64 * 100.0 / source.max(1) as f64
}

impl Plan {
    fn from_analysis(
        workspace: PathBuf,
        review_directory: PathBuf,
        analysis: Vec<AnalyzedImage>,
    ) -> rootcause::Result<Self> {
        let mut grouped: BTreeMap<GroupKey, Vec<AnalyzedImage>> =
            BTreeMap::new();
        for image in analysis {
            grouped
                .entry(GroupKey::from_features(image.features))
                .or_default()
                .push(image);
        }

        let mut recipes = BTreeMap::new();
        let mut groups = Vec::new();
        for (key, mut images) in grouped {
            images.sort_by(|left, right| {
                left.image.path.cmp(&right.image.path)
            });
            let metrics = group_metrics(&images);
            let representative_index =
                representative_index(&images, metrics);
            let representative_image = images
                .get(representative_index)
                .context("group has no representative")?;
            let representative =
                relative_to(&workspace, &representative_image.image.path)?;
            let recommendation = recipes_for_group(key, metrics);
            for (name, recipe) in recommendation.recipes {
                match recipes.entry(name) {
                    std::collections::btree_map::Entry::Vacant(entry) => {
                        entry.insert(recipe);
                    }
                    std::collections::btree_map::Entry::Occupied(
                        entry,
                    ) => {
                        if entry.get() != &recipe {
                            bail!(
                                "recipe name {} has conflicting definitions",
                                entry.key()
                            );
                        }
                    }
                }
            }
            let files = images
                .iter()
                .map(|entry| {
                    PlannedFile::from_path(
                        relative_to(&workspace, &entry.image.path)?,
                        &entry.image.path,
                    )
                })
                .collect::<rootcause::Result<Vec<_>>>()?;
            let selected_recipe = recommendation.selected;
            let mut candidate_recipes = vec![selected_recipe.clone()];
            candidate_recipes.extend(recommendation.alternatives);
            groups.push(PlanGroup {
                id: key.id(),
                selected_recipe,
                candidate_recipes,
                review_required: recommendation.review_required,
                reasons: recommendation.reasons,
                metrics,
                representative,
                files,
            });
        }

        Ok(Self {
            version: PLAN_VERSION,
            workspace,
            review_directory,
            recipes,
            groups,
        })
    }

    fn read(path: &Path) -> rootcause::Result<Self> {
        let raw = std::fs::read_to_string(path)
            .context_with(|| format!("read plan {}", path.display()))?;
        let plan = serde_json::from_str(&raw)
            .context_with(|| format!("parse plan {}", path.display()))?;
        Ok(plan)
    }

    fn write(&self, path: &Path, replace: bool) -> rootcause::Result<()> {
        if !replace && path.exists() {
            bail!("refusing to replace existing plan {}", path.display());
        }
        write_json_atomic(self, path)
    }

    fn validate(&self) -> rootcause::Result<()> {
        if self.version != PLAN_VERSION {
            bail!(
                "plan version mismatch: expected {PLAN_VERSION}, got {}",
                self.version
            );
        }
        if !self.workspace.is_absolute() {
            bail!("plan workspace must be absolute");
        }
        if !self.workspace.is_dir() {
            bail!("plan workspace is not a directory");
        }
        if !self.review_directory.is_absolute() {
            bail!("plan review directory must be absolute");
        }
        if self.review_directory == self.workspace
            || self.workspace.starts_with(&self.review_directory)
            || self
                .review_directory
                .starts_with(self.workspace.join(BACKUP_DIR_NAME))
        {
            bail!(
                "plan review directory is unsafe: {}",
                self.review_directory.display()
            );
        }
        if self.groups.is_empty() {
            bail!("plan has no groups");
        }
        if self.recipes.is_empty() {
            bail!("plan has no recipes");
        }

        for (name, recipe) in &self.recipes {
            if !valid_id(name) {
                bail!("invalid recipe id: {name}");
            }
            validate_automation_recipe(name, recipe)?;
        }

        let mut group_ids = BTreeSet::new();
        let mut paths = BTreeSet::new();
        for group in &self.groups {
            if !valid_id(&group.id) {
                bail!("invalid group id: {}", group.id);
            }
            if !group_ids.insert(&group.id) {
                bail!("duplicate group id: {}", group.id);
            }
            if group.files.is_empty() {
                bail!("group {} has no files", group.id);
            }
            if !group
                .files
                .iter()
                .any(|file| file.path == group.representative)
            {
                bail!("group {} representative is not a member", group.id);
            }

            if group.candidate_recipes.is_empty() {
                bail!("group {} has no candidate recipes", group.id);
            }
            let mut referenced_recipes = BTreeSet::new();
            for name in &group.candidate_recipes {
                if !referenced_recipes.insert(name) {
                    bail!(
                        "group {} references recipe {name} more than once",
                        group.id
                    );
                }
                if !self.recipes.contains_key(name) {
                    bail!(
                        "group {} references unknown recipe {name}",
                        group.id
                    );
                }
            }
            if !referenced_recipes.contains(&group.selected_recipe) {
                bail!(
                    "group {} selects recipe {} outside its candidates",
                    group.id,
                    group.selected_recipe
                );
            }

            for file in &group.files {
                validate_relative_path(&file.path)?;
                if !paths.insert(&file.path) {
                    bail!(
                        "image appears in more than one group: {}",
                        file.path.display()
                    );
                }
                let format = ImageFormat::from_path(&file.path)
                    .context_with(|| {
                        format!(
                            "unsupported planned image {}",
                            file.path.display()
                        )
                    })?;
                for name in group.recipe_names() {
                    self.recipes
                        .get(name)
                        .context("recipe reference was validated")?
                        .validate_for(format)
                        .context_with(|| {
                            format!(
                                "recipe {name} cannot process {}",
                                file.path.display()
                            )
                        })?;
                }
            }
        }
        Ok(())
    }

    fn validate_source_metadata(&self) -> rootcause::Result<()> {
        for group in &self.groups {
            for file in &group.files {
                self.resolve_planned_source(file)?;
            }
        }
        Ok(())
    }

    fn resolve_planned_source(
        &self,
        file: &PlannedFile,
    ) -> rootcause::Result<PathBuf> {
        let source = self.workspace.join(&file.path);
        if file.matches_metadata(&source)? {
            return Ok(source);
        }
        let backup = backup_path(&self.workspace, &source);
        if file.matches_metadata(&backup)? {
            return Ok(backup);
        }
        bail!(
            "{} changed or disappeared since the plan was generated (backup metadata also does not match)",
            file.path.display()
        )
    }
}

fn validate_automation_recipe(
    name: &str,
    recipe: &Recipe,
) -> rootcause::Result<()> {
    let input_formats = recipe
        .first_input_formats()
        .context_with(|| format!("recipe {name} has no steps"))?;
    if input_formats.is_empty() {
        bail!("recipe {name} accepts no input formats");
    }
    for format in input_formats {
        let output = recipe
            .validate_for(*format)
            .context_with(|| format!("invalid recipe {name}"))?;
        if !matches!(output, ImageFormat::AVIF | ImageFormat::JXL) {
            bail!("automation recipe {name} must end in AVIF or JXL");
        }
    }
    Ok(())
}

impl PlanGroup {
    fn recipe_names(&self) -> impl Iterator<Item = &String> {
        std::iter::once(&self.selected_recipe).chain(
            self.candidate_recipes
                .iter()
                .filter(|name| *name != &self.selected_recipe),
        )
    }
}

impl PlannedFile {
    fn from_path(
        path: PathBuf,
        absolute: &Path,
    ) -> rootcause::Result<Self> {
        let metadata = std::fs::metadata(absolute)?;
        let modified = metadata.modified()?.duration_since(UNIX_EPOCH)?;
        Ok(Self {
            path,
            bytes: metadata.len(),
            modified_unix_seconds: modified.as_secs(),
            modified_subsec_nanos: modified.subsec_nanos(),
        })
    }

    fn matches_metadata(&self, path: &Path) -> rootcause::Result<bool> {
        let Ok(metadata) = std::fs::metadata(path) else {
            return Ok(false);
        };
        if !metadata.is_file() || metadata.len() != self.bytes {
            return Ok(false);
        }
        let modified = metadata.modified()?.duration_since(UNIX_EPOCH)?;
        Ok(modified.as_secs() == self.modified_unix_seconds
            && modified.subsec_nanos() == self.modified_subsec_nanos)
    }
}

struct Recommendation {
    selected: String,
    alternatives: Vec<String>,
    review_required: bool,
    reasons: Vec<String>,
    recipes: Vec<(String, Recipe)>,
}

fn recipes_for_group(
    key: GroupKey,
    metrics: GroupMetrics,
) -> Recommendation {
    if key.content == ContentClass::LineArt {
        let name = "jxl-lossless".to_owned();
        return Recommendation {
            selected: name.clone(),
            alternatives: Vec::new(),
            review_required: false,
            reasons: vec![
                "Decoded pixels contain only black/white grayscale values; no thresholding is needed."
                    .to_owned(),
                "JPEG XL is mathematically lossless and races two modular strategies."
                    .to_owned(),
            ],
            recipes: vec![(name, Recipe::single(Step::Jxl(Jxl::default())))],
        };
    }

    let quality = quality_for(key.scale);
    let resolution = resolution_name(key.scale);
    let safe_name = format!("avif-safe-{resolution}");
    let safe_recipe = avif_recipe(quality, Chroma::Auto, false);
    if let ContentClass::MangaSandTone(burden) = key.content {
        return sand_tone_recommendation(
            quality,
            resolution,
            safe_name,
            safe_recipe,
            burden,
            metrics,
        );
    }

    let is_color = matches!(
        key.content,
        ContentClass::Color | ContentClass::TexturedColor
    );
    let is_grayscale = matches!(
        key.content,
        ContentClass::Grayscale
            | ContentClass::TexturedGrayscale
            | ContentClass::DegradedScan
    );
    let compact_quality = quality.saturating_sub(COMPACT_QUALITY_DELTA);
    let (compact_name, compact_chroma) = if is_color {
        (format!("avif-color-compact-{resolution}"), Chroma::Yuv420)
    } else {
        (format!("avif-grayscale-compact-{resolution}"), Chroma::Auto)
    };
    let compact_recipe =
        avif_recipe(compact_quality, compact_chroma, false);
    let mut recommendation = Recommendation {
        selected: safe_name.clone(),
        alternatives: vec![compact_name.clone()],
        review_required: false,
        reasons: vec![format!(
            "Content evidence: {:.1}% color, {:.1}% near black/white, entropy {:.2}, {:.1}% microtexture (directional coherence {:.2}).",
            metrics.color_percent,
            metrics.near_bw_percent,
            metrics.gray_entropy,
            metrics.microtexture_percent,
            metrics.texture_directional_coherence,
        )],
        recipes: vec![
            (safe_name, safe_recipe),
            (compact_name, compact_recipe),
        ],
    };

    if key.content == ContentClass::TexturedColor {
        let grain_name = format!("avif-color-grain-{resolution}");
        recommendation.alternatives.push(grain_name.clone());
        recommendation.recipes.push((
            grain_name,
            avif_recipe(quality, Chroma::Yuv420, true),
        ));
        recommendation.review_required = true;
        recommendation.reasons.push(
            "Color texture is dense enough for AOM grain synthesis to be a candidate; it changes texture and requires 1:1 review."
                .to_owned(),
        );
    }

    if is_grayscale {
        recommendation.reasons.push(format!(
            "Binarization evidence: {:.1} mean binary error, {:.1}% threshold-sensitive pixels, {:.1}% smooth midtones.",
            metrics.binary_error_mean,
            metrics.threshold_stability_percent,
            metrics.smooth_midtone_percent,
        ));
        let has_regional_tone = metrics.sand_tone_region_percent > 0.0;
        if key.content != ContentClass::DegradedScan
            && (key.content == ContentClass::TexturedGrayscale
                || has_regional_tone)
        {
            let strength = regional_sand_tone_strength(metrics);
            let regional_name = format!(
                "flatten-sand-tone-{}-{resolution}",
                sand_tone_strength_name(strength),
            );
            recommendation.alternatives.push(regional_name.clone());
            recommendation.recipes.push((
                regional_name,
                flatten_sand_tone_avif_recipe(quality, strength),
            ));
            recommendation.review_required = true;
            if has_regional_tone {
                recommendation.reasons.push(format!(
                    "Regional analysis found {:.1}% candidate tone area at {:.1}% local microtexture; selective flattening is offered without changing smooth regions.",
                    metrics.sand_tone_region_percent,
                    metrics.sand_tone_region_microtexture_percent,
                ));
            } else {
                recommendation.reasons.push(
                    "The page is textured but lacks confident sand-tone evidence; selective light flattening remains review-only and its mask may leave the page unchanged."
                        .to_owned(),
                );
            }
        }
        if key.content == ContentClass::TexturedGrayscale {
            let bilateral_name =
                format!("grayscale-bilateral-{resolution}");
            recommendation.alternatives.push(bilateral_name.clone());
            recommendation.recipes.push((
                bilateral_name,
                Recipe::pair(
                    Step::Denoise(Denoise::default()),
                    Step::Avif(avif_options(quality, Chroma::Auto, false)),
                ),
            ));
            recommendation.review_required = true;
        }
        if metrics.near_bw_percent >= NEAR_BILEVEL_REVIEW_PERCENT
            || key.content == ContentClass::DegradedScan
        {
            let bilevel_name = "clean-scan-jxl".to_owned();
            if key.content == ContentClass::DegradedScan {
                let previous = std::mem::replace(
                    &mut recommendation.selected,
                    bilevel_name.clone(),
                );
                recommendation.alternatives.push(previous);
                recommendation.reasons.push(
                    "The degraded-scan category selects threshold cleanup and mathematically lossless JPEG XL."
                        .to_owned(),
                );
            } else {
                recommendation.alternatives.push(bilevel_name.clone());
                recommendation.reasons.push(
                    "The page is near-bilevel but did not meet every degraded-scan check; threshold cleanup remains review-only."
                        .to_owned(),
                );
            }
            recommendation.recipes.push((
                bilevel_name,
                Recipe::pair(
                    Step::CleanScan(CleanScan::default()),
                    Step::Jxl(Jxl::default()),
                ),
            ));
            recommendation.review_required = true;
        }
        if metrics.near_bw_percent < PENCIL_MAX_NEAR_BW_PERCENT
            && metrics.gray_entropy >= PENCIL_MIN_GRAY_ENTROPY
            && metrics.soft_noise_percent >= PENCIL_MIN_SOFT_NOISE_PERCENT
        {
            let despeckle_name =
                format!("grayscale-despeckle-{resolution}");
            recommendation.alternatives.push(despeckle_name.clone());
            recommendation.recipes.push((
                despeckle_name,
                Recipe::pair(
                    Step::Denoise(Denoise {
                        mode: Mode::Despeckle,
                        strength: None,
                    }),
                    Step::Avif(avif_options(quality, Chroma::Auto, false)),
                ),
            ));
            recommendation.review_required = true;
            recommendation.reasons.push(
                "Broad grayscale texture resembles stylized pencil/speckle; edge-preserving despeckle is offered for review."
                    .to_owned(),
            );
        }
    }

    recommendation.alternatives.sort();
    recommendation.alternatives.dedup();
    recommendation
}

fn sand_tone_recommendation(
    quality: u8,
    resolution: &str,
    safe_name: String,
    safe_recipe: Recipe,
    burden: SandToneBurden,
    metrics: GroupMetrics,
) -> Recommendation {
    let light_name = format!("flatten-sand-tone-light-{resolution}");
    let medium_name = format!("flatten-sand-tone-medium-{resolution}");
    let heavy_name = format!("flatten-sand-tone-heavy-{resolution}");
    let (selected, alternatives) = match burden {
        SandToneBurden::Light => (
            light_name.clone(),
            vec![
                safe_name.clone(),
                medium_name.clone(),
                heavy_name.clone(),
            ],
        ),
        SandToneBurden::Medium => (
            medium_name.clone(),
            vec![
                safe_name.clone(),
                light_name.clone(),
                heavy_name.clone(),
            ],
        ),
        SandToneBurden::Heavy => (
            heavy_name.clone(),
            vec![
                safe_name.clone(),
                light_name.clone(),
                medium_name.clone(),
            ],
        ),
    };
    Recommendation {
        selected,
        alternatives,
        review_required: true,
        reasons: vec![
            format!(
                "Manga sand-tone evidence: {:.1}% global microtexture, {:.1}% regional coverage at {:.1}% local microtexture, {:.2} directional coherence.",
                metrics.microtexture_percent,
                metrics.sand_tone_region_percent,
                metrics.sand_tone_region_microtexture_percent,
                metrics.texture_directional_coherence,
            ),
            format!(
                "{} sand-tone burden selects masked low-pass filtering and grayscale quantization only inside large dense-texture regions.",
                sand_tone_burden_name(burden),
            ),
        ],
        recipes: vec![
            (
                light_name,
                flatten_sand_tone_avif_recipe(
                    quality,
                    SandToneStrength::Light,
                ),
            ),
            (
                medium_name,
                flatten_sand_tone_avif_recipe(
                    quality,
                    SandToneStrength::Medium,
                ),
            ),
            (
                heavy_name,
                flatten_sand_tone_avif_recipe(
                    quality,
                    SandToneStrength::Heavy,
                ),
            ),
            (safe_name, safe_recipe),
        ],
    }
}

const fn sand_tone_strength_name(
    strength: SandToneStrength,
) -> &'static str {
    match strength {
        SandToneStrength::Light => "light",
        SandToneStrength::Medium => "medium",
        SandToneStrength::Heavy => "heavy",
    }
}

fn regional_sand_tone_strength(metrics: GroupMetrics) -> SandToneStrength {
    match metrics.sand_tone_region_microtexture_percent {
        microtexture
            if microtexture
                < REGIONAL_SAND_TONE_LIGHT_MAX_MICROTEXTURE_PERCENT =>
        {
            SandToneStrength::Light
        }
        microtexture
            if microtexture
                < REGIONAL_SAND_TONE_MEDIUM_MAX_MICROTEXTURE_PERCENT =>
        {
            SandToneStrength::Medium
        }
        _ => SandToneStrength::Heavy,
    }
}

const fn sand_tone_burden_name(burden: SandToneBurden) -> &'static str {
    match burden {
        SandToneBurden::Light => "Light",
        SandToneBurden::Medium => "Medium",
        SandToneBurden::Heavy => "Heavy",
    }
}

fn flatten_sand_tone_avif_recipe(
    quality: u8,
    strength: SandToneStrength,
) -> Recipe {
    Recipe::pair(
        Step::FlattenSandTone(FlattenSandTone { strength }),
        Step::Avif(avif_options_with_speed(
            quality,
            Chroma::Auto,
            false,
            SAND_TONE_AVIF_SPEED,
        )),
    )
}

fn avif_recipe(quality: u8, chroma: Chroma, grain: bool) -> Recipe {
    Recipe::single(Step::Avif(avif_options(quality, chroma, grain)))
}

fn avif_options(quality: u8, chroma: Chroma, grain: bool) -> Avif {
    avif_options_with_speed(quality, chroma, grain, Avif::default().speed)
}

fn avif_options_with_speed(
    quality: u8,
    chroma: Chroma,
    grain: bool,
    speed: u8,
) -> Avif {
    Avif {
        quality,
        chroma,
        grain,
        speed,
        ..Avif::default()
    }
}

const fn quality_for(scale: ScaleClass) -> u8 {
    match scale {
        // Smaller canvases receive more quality because defects occupy more of
        // the viewed image. Large pages are tuned for a 2k-ish viewing scale.
        ScaleClass::Small => SMALL_AVIF_QUALITY,
        ScaleClass::Medium => MEDIUM_AVIF_QUALITY,
        ScaleClass::Large => LARGE_AVIF_QUALITY,
    }
}

const fn resolution_name(scale: ScaleClass) -> &'static str {
    match scale {
        ScaleClass::Small => "low-resolution",
        ScaleClass::Medium => "standard-resolution",
        ScaleClass::Large => "high-resolution",
    }
}

fn group_metrics(images: &[AnalyzedImage]) -> GroupMetrics {
    let count = f64::from(u32::try_from(images.len()).unwrap_or(u32::MAX));
    let average = |select: fn(ImageFeatures) -> f64| {
        images
            .iter()
            .map(|image| select(image.features))
            .sum::<f64>()
            / count
    };
    GroupMetrics {
        color_percent: average(|features| features.color_percent),
        gray_entropy: average(|features| features.gray_entropy),
        near_bw_percent: average(|features| features.near_bw_percent),
        detail_percent: average(|features| features.detail_percent),
        soft_noise_percent: average(|features| {
            features.soft_noise_percent
        }),
        max_tile_soft_noise_percent: average(|features| {
            features.max_tile_soft_noise_percent
        }),
        microtexture_percent: average(ImageFeatures::microtexture_percent),
        texture_directional_coherence: average(|features| {
            features.texture_directional_coherence
        }),
        sand_tone_region_percent: average(|features| {
            features.sand_tone_region_percent
        }),
        sand_tone_region_microtexture_percent: average(|features| {
            features.sand_tone_region_microtexture_percent
        }),
        threshold_stability_percent: average(|features| {
            features.threshold_stability_percent
        }),
        binary_error_mean: average(|features| features.binary_error_mean),
        smooth_midtone_percent: average(|features| {
            features.smooth_midtone_percent
        }),
        min_longest_edge: images
            .iter()
            .map(|image| image.features.longest_edge())
            .min()
            .unwrap_or(0),
        max_longest_edge: images
            .iter()
            .map(|image| image.features.longest_edge())
            .max()
            .unwrap_or(0),
    }
}

fn representative_index(
    images: &[AnalyzedImage],
    metrics: GroupMetrics,
) -> usize {
    images
        .iter()
        .enumerate()
        .min_by(|(_, left), (_, right)| {
            feature_distance(left.features, metrics)
                .total_cmp(&feature_distance(right.features, metrics))
        })
        .map_or(0, |(index, _)| index)
}

fn feature_distance(
    features: ImageFeatures,
    metrics: GroupMetrics,
) -> f64 {
    (features.color_percent - metrics.color_percent).abs() / 100.0
        + (features.near_bw_percent - metrics.near_bw_percent).abs()
            / 100.0
        + (features.gray_entropy - metrics.gray_entropy).abs() / 8.0
        + (features.microtexture_percent() - metrics.microtexture_percent)
            .abs()
            / 100.0
        + (features.max_tile_soft_noise_percent
            - metrics.max_tile_soft_noise_percent)
            .abs()
            / 100.0
        + (features.texture_directional_coherence
            - metrics.texture_directional_coherence)
            .abs()
        + (features.sand_tone_region_percent
            - metrics.sand_tone_region_percent)
            .abs()
            / 100.0
        + (features.sand_tone_region_microtexture_percent
            - metrics.sand_tone_region_microtexture_percent)
            .abs()
            / 100.0
}

fn relative_to(
    workspace: &Path,
    path: &Path,
) -> rootcause::Result<PathBuf> {
    let relative = path.strip_prefix(workspace).map(Path::to_path_buf);
    Ok(relative.context_with(|| {
        format!(
            "{} is outside workspace {}",
            path.display(),
            workspace.display()
        )
    })?)
}

fn validate_relative_path(path: &Path) -> rootcause::Result<()> {
    if path.as_os_str().is_empty() {
        bail!("empty image path");
    }
    if path.is_absolute() {
        bail!("planned image path must be relative");
    }
    if !path
        .components()
        .all(|component| matches!(component, Component::Normal(_)))
    {
        bail!(
            "planned image path contains traversal or special components: {}",
            path.display()
        );
    }
    Ok(())
}

fn valid_id(id: &str) -> bool {
    !id.is_empty()
        && id.bytes().all(|byte| {
            byte.is_ascii_lowercase()
                || byte.is_ascii_digit()
                || byte == b'-'
        })
}

fn analysis_progress(
    length: usize,
    jobs: NonZeroU64,
) -> rootcause::Result<ProgressBar> {
    let progress = ProgressBar::new(u64::try_from(length)?);
    progress.set_style(
        ProgressStyle::with_template(
            "Analyzing ({msg} workers) [{elapsed_precise}] [{bar:40.blue/gray}] {pos}/{len} ({eta})",
        )?
        .progress_chars("#>-"),
    );
    progress.set_message(jobs.to_string());
    progress.enable_steady_tick(Duration::from_millis(100));
    Ok(progress)
}

fn default_analysis_jobs() -> NonZeroU64 {
    let available =
        std::thread::available_parallelism().map_or(1, usize::from);
    let selected = u64::try_from(available.clamp(1, 4)).unwrap_or(1);
    #[expect(
        clippy::unwrap_used,
        reason = "selected is clamped to at least one"
    )]
    NonZeroU64::new(selected).unwrap()
}

fn print_plan_summary(plan: &Plan, output: &Path) {
    let image_count: usize =
        plan.groups.iter().map(|group| group.files.len()).sum();
    println!(
        "Plan: {} images in {} content groups -> {}",
        image_count,
        plan.groups.len(),
        output.display()
    );
    for group in &plan.groups {
        let review = if group.review_required {
            "review required"
        } else {
            "safe direct route"
        };
        println!(
            "  {:52} {:>4} images  {:52}  {review}",
            group.id,
            group.files.len(),
            group.selected_recipe,
        );
        for reason in &group.reasons {
            println!("    {reason}");
        }
    }
}

#[cfg(test)]
#[expect(clippy::panic_in_result_fn, reason = "test assertions")]
#[expect(clippy::unwrap_used, reason = "test verifies a rejected result")]
mod tests {
    use super::*;

    fn metrics(near_bw_percent: f64) -> GroupMetrics {
        GroupMetrics {
            color_percent: 0.0,
            gray_entropy: 4.0,
            near_bw_percent,
            detail_percent: 10.0,
            soft_noise_percent: 4.0,
            max_tile_soft_noise_percent: 12.0,
            microtexture_percent: 14.0,
            texture_directional_coherence: 0.2,
            sand_tone_region_percent: 0.0,
            sand_tone_region_microtexture_percent: 0.0,
            threshold_stability_percent: 10.0,
            binary_error_mean: 20.0,
            smooth_midtone_percent: 10.0,
            min_longest_edge: 4000,
            max_longest_edge: 4000,
        }
    }

    #[test]
    fn ambiguous_near_bilevel_recipe_remains_unselected() {
        let recommendation = recipes_for_group(
            GroupKey {
                content: ContentClass::Grayscale,
                scale: ScaleClass::Large,
            },
            metrics(78.0),
        );
        assert_eq!(recommendation.selected, "avif-safe-high-resolution");
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name == "clean-scan-jxl")
        );
        assert!(recommendation.review_required);
    }

    #[test]
    fn threshold_stable_large_page_selects_clean_scan() {
        let mut stable_metrics = metrics(65.5);
        stable_metrics.threshold_stability_percent = 4.2;
        stable_metrics.binary_error_mean = 17.8;
        stable_metrics.smooth_midtone_percent = 0.4;
        let recommendation = recipes_for_group(
            GroupKey {
                content: ContentClass::DegradedScan,
                scale: ScaleClass::Large,
            },
            stable_metrics,
        );

        assert_eq!(recommendation.selected, "clean-scan-jxl");
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name == "avif-safe-high-resolution")
        );
    }

    #[test]
    fn grain_synthesis_is_an_unselected_color_alternative() {
        let mut color_metrics = metrics(1.0);
        color_metrics.color_percent = 98.0;
        color_metrics.soft_noise_percent = 40.0;
        let recommendation = recipes_for_group(
            GroupKey {
                content: ContentClass::TexturedColor,
                scale: ScaleClass::Small,
            },
            color_metrics,
        );
        assert_eq!(recommendation.selected, "avif-safe-low-resolution");
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name == "avif-color-grain-low-resolution")
        );
    }

    #[test]
    fn measured_sand_tone_selects_masked_flattening() {
        let mut sand_metrics = metrics(54.3);
        sand_metrics.gray_entropy = 5.08;
        sand_metrics.soft_noise_percent = 7.0;
        sand_metrics.max_tile_soft_noise_percent = 45.1;
        sand_metrics.microtexture_percent = 35.0;
        sand_metrics.texture_directional_coherence = 0.08;
        sand_metrics.smooth_midtone_percent = 30.5;
        let recommendation = recipes_for_group(
            GroupKey {
                content: ContentClass::MangaSandTone(
                    SandToneBurden::Medium,
                ),
                scale: ScaleClass::Medium,
            },
            sand_metrics,
        );

        assert_eq!(
            recommendation.selected,
            "flatten-sand-tone-medium-standard-resolution"
        );
        assert!(recommendation.review_required);
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name == "avif-safe-standard-resolution")
        );
        let expected = Recipe::pair(
            Step::FlattenSandTone(FlattenSandTone {
                strength: SandToneStrength::Medium,
            }),
            Step::Avif(Avif {
                quality: MEDIUM_AVIF_QUALITY,
                speed: SAND_TONE_AVIF_SPEED,
                ..Avif::default()
            }),
        );
        assert!(recommendation.recipes.iter().any(|(name, recipe)| {
            name == "flatten-sand-tone-medium-standard-resolution"
                && recipe == &expected
        }));
    }

    #[test]
    fn weak_regional_evidence_offers_unselected_masked_flattening() {
        let mut regional_metrics = metrics(60.0);
        regional_metrics.sand_tone_region_percent = 0.8;
        regional_metrics.sand_tone_region_microtexture_percent = 31.0;
        let recommendation = recipes_for_group(
            GroupKey {
                content: ContentClass::Grayscale,
                scale: ScaleClass::Large,
            },
            regional_metrics,
        );

        assert_eq!(recommendation.selected, "avif-safe-high-resolution");
        assert!(recommendation.review_required);
        assert!(recommendation.alternatives.iter().any(|name| {
            name == "flatten-sand-tone-light-high-resolution"
        }));
    }

    #[test]
    fn metadata_numbers_survive_javascript_editors()
    -> rootcause::Result<()> {
        const JS_MAX_SAFE_INTEGER: u64 = 0x001F_FFFF_FFFF_FFFF;

        let directory = tempfile::tempdir()?;
        let path = directory.path().join("image.png");
        std::fs::write(&path, b"pixels")?;
        let metadata =
            PlannedFile::from_path(PathBuf::from("image.png"), &path)?;
        assert!(metadata.modified_unix_seconds < JS_MAX_SAFE_INTEGER);
        assert!(
            u64::from(metadata.modified_subsec_nanos)
                < JS_MAX_SAFE_INTEGER
        );

        let mut value = serde_json::to_value(&metadata)?;
        let object = value
            .as_object_mut()
            .context("planned file did not serialize as an object")?;
        assert!(!object.contains_key("modified_unix_ns"));
        object.insert(
            "unexpected".to_owned(),
            serde_json::Value::Bool(true),
        );
        serde_json::from_value::<PlannedFile>(value).unwrap_err();
        Ok(())
    }

    #[test]
    fn selected_recipe_can_change_without_rewriting_candidates()
    -> rootcause::Result<()> {
        let directory = tempfile::tempdir()?;
        let safe = "safe".to_owned();
        let compact = "compact".to_owned();
        let plan = Plan {
            version: PLAN_VERSION,
            workspace: directory.path().to_path_buf(),
            review_directory: directory.path().join(REVIEW_DIR_NAME),
            recipes: BTreeMap::from([
                (
                    safe.clone(),
                    Recipe::single(Step::Avif(Avif::default())),
                ),
                (
                    compact.clone(),
                    Recipe::single(Step::Avif(Avif {
                        quality: 58,
                        ..Avif::default()
                    })),
                ),
            ]),
            groups: vec![PlanGroup {
                id: "grayscale-low-resolution".to_owned(),
                selected_recipe: compact.clone(),
                candidate_recipes: vec![safe, compact],
                review_required: false,
                reasons: Vec::new(),
                metrics: metrics(50.0),
                representative: PathBuf::from("page.png"),
                files: vec![PlannedFile {
                    path: PathBuf::from("page.png"),
                    bytes: 1,
                    modified_unix_seconds: 0,
                    modified_subsec_nanos: 0,
                }],
            }],
        };

        plan.validate()
    }

    #[test]
    fn all_recipe_definitions_must_end_in_an_archive_format() {
        let png_only = Recipe::single(Step::Denoise(Denoise::default()));
        validate_automation_recipe("png-only", &png_only).unwrap_err();
    }

    #[test]
    fn review_names_map_source_and_recipe() {
        let planned = PlannedFile {
            path: PathBuf::from("chapter/001.png"),
            bytes: 1,
            modified_unix_seconds: 0,
            modified_subsec_nanos: 0,
        };
        let group = PlanGroup {
            id: "textured-grayscale-high-resolution".to_owned(),
            selected_recipe: "safe".to_owned(),
            candidate_recipes: vec!["safe".to_owned()],
            review_required: false,
            reasons: Vec::new(),
            metrics: metrics(50.0),
            representative: planned.path.clone(),
            files: vec![planned.clone()],
        };

        assert_eq!(
            review_group_directory_name(0, &group, &planned),
            "001--textured-grayscale-high-resolution--001"
        );
        assert_eq!(
            candidate_artifact_file_name(1, "safe", "avif"),
            "01--safe.avif"
        );
        assert_eq!(
            candidate_artifact_file_name(2, "compact", "jxl"),
            "02--compact.jxl"
        );
    }

    #[test]
    fn reviewed_artifact_requires_exact_source_and_recipe()
    -> rootcause::Result<()> {
        let directory = tempfile::tempdir()?;
        let review = directory.path().join(REVIEW_DIR_NAME);
        let artifact_relative =
            PathBuf::from("001--group--page/01-selected--safe.avif");
        let artifact = review.join(&artifact_relative);
        std::fs::create_dir_all(
            artifact.parent().context("artifact parent")?,
        )?;
        std::fs::write(&artifact, b"encoded")?;
        let source_path = directory.path().join("page.png");
        std::fs::write(&source_path, b"source")?;
        let planned = PlannedFile::from_path(
            PathBuf::from("page.png"),
            &source_path,
        )?;
        let recipe = Recipe::single(Step::Avif(Avif::default()));
        let metadata = std::fs::metadata(&artifact)?;
        let modified = metadata.modified()?.duration_since(UNIX_EPOCH)?;
        let manifest = ReviewManifest {
            version: REVIEW_VERSION,
            workspace: directory.path().to_path_buf(),
            candidates: vec![ReviewedCandidate {
                source: planned.clone(),
                recipe_name: "safe".to_owned(),
                recipe: recipe.clone(),
                artifact: artifact_relative,
                output_extension: "avif".to_owned(),
                encoded_modified_unix_seconds: modified.as_secs(),
                encoded_modified_subsec_nanos: modified.subsec_nanos(),
                encoded_bytes: metadata.len(),
            }],
        };

        assert!(
            reviewed_candidate(
                &manifest,
                &review,
                &planned,
                ImageFormat::PNG,
                "safe",
                &recipe,
            )?
            .is_some()
        );
        let changed_recipe = Recipe::single(Step::Avif(Avif {
            quality: 64,
            ..Avif::default()
        }));
        assert!(
            reviewed_candidate(
                &manifest,
                &review,
                &planned,
                ImageFormat::PNG,
                "safe",
                &changed_recipe,
            )?
            .is_none()
        );
        let mut changed_source = planned;
        changed_source.bytes += 1;
        assert!(
            reviewed_candidate(
                &manifest,
                &review,
                &changed_source,
                ImageFormat::PNG,
                "safe",
                &recipe,
            )?
            .is_none()
        );
        Ok(())
    }

    #[test]
    fn unmanaged_review_requires_force() -> rootcause::Result<()> {
        let directory = tempfile::tempdir()?;
        let output = directory.path().join(REVIEW_DIR_NAME);
        std::fs::create_dir_all(&output)?;

        validate_review_target(&output, directory.path(), false)
            .unwrap_err();
        validate_review_target(&output, directory.path(), true)?;
        write_json_atomic(
            &ReviewManifest {
                version: REVIEW_VERSION,
                workspace: directory.path().to_path_buf(),
                candidates: Vec::new(),
            },
            &output.join(REVIEW_MANIFEST_NAME),
        )?;
        validate_review_target(&output, directory.path(), false)
    }
}
