use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::io::Write as _;
use std::num::NonZeroU64;
use std::path::Component;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::UNIX_EPOCH;

use anyhow::Context as _;
use anyhow::bail;
use anyhow::ensure;
use rayon::ThreadPoolBuilder;
use rayon::prelude::*;
use serde::Deserialize;
use serde::Serialize;
use tempfile::Builder;

use crate::REVIEW_DIR_NAME;
use crate::classify::AnalyzedImage;
use crate::classify::GroupKey;
use crate::classify::ImageFeatures;
use crate::classify::PaletteClass;
use crate::classify::ScaleClass;
use crate::classify::TextureClass;
use crate::classify::analyze;
use crate::fs::backup_path;
use crate::fs::collect_images;
use crate::img::Image;
use crate::img::ImageFormat;
use crate::pipeline::Job;
use crate::pipeline::run_jobs;
use crate::recipe::Recipe;
use crate::recipe::Step;
use crate::transcoder::Tool;
use crate::transcoder::avif::Avif;
use crate::transcoder::avif::Chroma;
use crate::transcoder::jxl::Jxl;
use crate::transcoder::magick::CleanScan;
use crate::transcoder::magick::Denoise;
use crate::transcoder::magick::Mode;
use crate::transcoder::run_command;

const PLAN_VERSION: u32 = 1;
const DEFAULT_PLAN_NAME: &str = "imgo-plan.json";

#[derive(Debug, clap::Args)]
pub struct PlanOpts {
    /// Directory containing source PNG/JPEG images.
    #[arg(default_value = ".")]
    pub workspace: PathBuf,

    /// JSON plan path. Defaults to `<workspace>/imgo-plan.json`.
    #[arg(long, short)]
    pub output: Option<PathBuf>,

    /// Analyze only immediate children of the workspace.
    #[arg(long, short = 'R', default_value_t = false)]
    pub no_recursive: bool,

    /// Number of images decoded concurrently (default: at most four).
    #[arg(long, short = 'J')]
    pub jobs: Option<NonZeroU64>,

    /// Replace an existing generated plan.
    #[arg(long, default_value_t = false)]
    pub force: bool,
}

#[derive(Debug, clap::Args)]
pub struct PreviewOpts {
    /// Plan generated by `i plan`.
    pub plan: PathBuf,

    /// Review output directory. Defaults to `<workspace>/.imgo-review`.
    #[arg(long, short)]
    pub output: Option<PathBuf>,
}

#[derive(Debug, clap::Args)]
pub struct RunOpts {
    /// Reviewed plan generated by `i plan`.
    pub plan: PathBuf,

    /// Number of images processed concurrently. Defaults to one because
    /// avifenc/cjxl use all cores internally.
    #[arg(long, short = 'J')]
    pub jobs: Option<NonZeroU64>,

    /// Keep originals in place. The default moves them into `.backup` and
    /// enables reliable resume detection.
    #[arg(long, short = 'N', default_value_t = false)]
    pub no_backup: bool,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
    version: u32,
    workspace: PathBuf,
    groups: Vec<PlanGroup>,
    recipes: BTreeMap<String, Recipe>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct PlanGroup {
    id: String,
    selected_recipe: String,
    alternative_recipes: Vec<String>,
    review_required: bool,
    reasons: Vec<String>,
    metrics: GroupMetrics,
    representative: PathBuf,
    files: Vec<PlannedFile>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct PlannedFile {
    path: PathBuf,
    bytes: u64,
    modified_unix_seconds: u64,
    modified_subsec_nanos: u32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct GroupMetrics {
    color_percent: f64,
    gray_entropy: f64,
    near_bw_percent: f64,
    detail_percent: f64,
    soft_noise_percent: f64,
    max_tile_soft_noise_percent: f64,
    min_longest_edge: u32,
    max_longest_edge: u32,
}

/// Analyze source images and write a versioned, editable execution plan.
///
/// # Errors
///
/// Returns an error for invalid paths, image decode failures, an existing
/// plan without `--force`, classifier failures, or plan serialization errors.
pub fn create_plan(options: &PlanOpts) -> anyhow::Result<()> {
    let workspace =
        options.workspace.canonicalize().with_context(|| {
            format!("resolve workspace {}", options.workspace.display())
        })?;
    ensure!(workspace.is_dir(), "workspace is not a directory");
    let output = options
        .output
        .clone()
        .unwrap_or_else(|| workspace.join(DEFAULT_PLAN_NAME));
    ensure!(
        options.force || !output.exists(),
        "plan already exists: {} (pass --force to replace it)",
        output.display()
    );

    let images = collect_images(
        &workspace,
        &[ImageFormat::PNG, ImageFormat::JPG],
        !options.no_recursive,
    )?;
    ensure!(!images.is_empty(), "no PNG/JPEG images found");
    let analysis_jobs = options.jobs.unwrap_or_else(default_analysis_jobs);
    let pool = ThreadPoolBuilder::new()
        .num_threads(usize::try_from(analysis_jobs.get())?)
        .build()
        .context("build classifier worker pool")?;
    let analysis = pool
        .install(|| {
            images.into_par_iter().map(analyze).collect::<Vec<_>>()
        })
        .into_iter()
        .collect::<anyhow::Result<Vec<_>>>()?;

    let plan = Plan::from_analysis(workspace, analysis)?;
    plan.validate()?;
    plan.write(&output, options.force)?;
    print_plan_summary(&plan, &output);
    Ok(())
}

/// Generate full-resolution representative outputs for every selected and
/// alternative recipe in a plan.
///
/// # Errors
///
/// Returns an error when the plan is invalid or stale, a required tool is
/// missing, a recipe fails, or a preview cannot be decoded or committed.
pub fn preview_plan(options: &PreviewOpts) -> anyhow::Result<()> {
    let plan = Plan::read(&options.plan)?;
    plan.validate()?;
    plan.validate_fingerprints()?;
    let output = options
        .output
        .clone()
        .unwrap_or_else(|| plan.workspace.join(REVIEW_DIR_NAME));

    let mut tools = BTreeSet::from([Tool::Magick]);
    for group in &plan.groups {
        for name in group.recipe_names() {
            plan.recipes
                .get(name)
                .with_context(|| format!("unknown recipe {name}"))?
                .required_tools(&mut tools);
        }
    }
    for tool in tools {
        tool.verify()?;
    }

    std::fs::create_dir_all(&output).with_context(|| {
        format!("create review directory {}", output.display())
    })?;
    println!("Review output: {}", output.display());
    for group in &plan.groups {
        let directory = output.join(&group.id);
        std::fs::create_dir_all(&directory)?;
        let planned = group
            .files
            .iter()
            .find(|file| file.path == group.representative)
            .context("representative is absent from its group")?;
        let source = plan.resolve_source(planned)?;
        let original_extension = ImageFormat::from_path(&source)
            .and_then(ImageFormat::primary_extension)
            .unwrap_or("img");
        std::fs::copy(
            &source,
            directory.join(format!("original.{original_extension}")),
        )?;

        println!("\n{} — {}", group.id, source.display());
        for name in group.recipe_names() {
            let recipe = plan
                .recipes
                .get(name)
                .with_context(|| format!("unknown recipe {name}"))?;
            let input_format = ImageFormat::from_path(&planned.path)
                .context("planned image has unsupported extension")?;
            let output_format = recipe.validate_for(input_format)?;
            let extension = output_format
                .primary_extension()
                .context("recipe output has no extension")?;
            let encoded_path =
                directory.join(format!("{name}.{extension}"));
            let temporary = Builder::new()
                .prefix(".preview-")
                .suffix(&format!(".{extension}"))
                .tempfile_in(&directory)?;
            recipe.execute(&source, input_format, temporary.path())?;
            ensure!(
                std::fs::metadata(temporary.path())?.len() > 0,
                "preview recipe {name} produced an empty output"
            );
            temporary
                .persist(&encoded_path)
                .map_err(|error| error.error)
                .with_context(|| {
                    format!("commit preview {}", encoded_path.display())
                })?;

            let decoded_path =
                directory.join(format!("{name}.preview.png"));
            let mut command = Tool::Magick.command();
            command.arg(&encoded_path);
            command.arg("-strip");
            command.arg(&decoded_path);
            run_command(
                "magick review decode",
                &encoded_path,
                &mut command,
            )?;
            let encoded_size = std::fs::metadata(&encoded_path)?.len();
            #[expect(
                clippy::cast_precision_loss,
                reason = "ratio is display-only and image file sizes are far below f64's exact integer limit"
            )]
            let ratio = encoded_size as f64 * 100.0 / planned.bytes as f64;
            let marker = if name == &group.selected_recipe {
                "selected"
            } else {
                "alternative"
            };
            println!(
                "  {marker:11} {name:34} {encoded_size:>10} bytes ({ratio:5.1}%)"
            );
        }
    }
    println!(
        "\nInspect each *.preview.png at 1:1, then edit selected_recipe in {}.",
        options.plan.display()
    );
    Ok(())
}

/// Execute all selected recipes in a validated plan.
///
/// # Errors
///
/// Returns an error when the plan is invalid or stale, preflight detects a
/// conflict, a tool is missing, or one or more image jobs fail.
pub fn run_plan(options: &RunOpts) -> anyhow::Result<()> {
    let plan = Plan::read(&options.plan)?;
    plan.validate()?;
    plan.validate_fingerprints()?;

    let mut recipe_cache: BTreeMap<String, Arc<Recipe>> = BTreeMap::new();
    for group in &plan.groups {
        if !recipe_cache.contains_key(&group.selected_recipe) {
            let recipe =
                plan.recipes.get(&group.selected_recipe).with_context(
                    || format!("unknown recipe {}", group.selected_recipe),
                )?;
            recipe_cache.insert(
                group.selected_recipe.clone(),
                Arc::new(recipe.clone()),
            );
        }
    }
    let mut jobs = Vec::new();
    for group in &plan.groups {
        let recipe = Arc::clone(
            recipe_cache
                .get(&group.selected_recipe)
                .context("selected recipe was not cached")?,
        );
        for file in &group.files {
            let path = plan.workspace.join(&file.path);
            let format = ImageFormat::from_path(&file.path)
                .context("planned image has unsupported extension")?;
            jobs.push(Job {
                image: Image { path, format },
                recipe: Arc::clone(&recipe),
            });
        }
    }

    let summary = run_jobs(
        &plan.workspace,
        jobs,
        options.no_backup,
        options.jobs.unwrap_or(NonZeroU64::MIN),
    )?;
    println!(
        "Processed {}, already complete {}.",
        summary.processed, summary.already_complete
    );
    Ok(())
}

impl Plan {
    fn from_analysis(
        workspace: PathBuf,
        analysis: Vec<AnalyzedImage>,
    ) -> anyhow::Result<Self> {
        let mut grouped: BTreeMap<GroupKey, Vec<AnalyzedImage>> =
            BTreeMap::new();
        for image in analysis {
            grouped
                .entry(GroupKey::from_features(image.features))
                .or_default()
                .push(image);
        }

        let mut recipes = BTreeMap::new();
        let mut groups = Vec::new();
        for (key, mut images) in grouped {
            images.sort_by(|left, right| {
                left.image.path.cmp(&right.image.path)
            });
            let metrics = group_metrics(&images);
            let representative_index =
                representative_index(&images, metrics);
            let representative_image = images
                .get(representative_index)
                .context("group has no representative")?;
            let representative =
                relative_to(&workspace, &representative_image.image.path)?;
            let recommendation = recipes_for_group(key, metrics);
            for (name, recipe) in recommendation.recipes {
                if let Some(existing) =
                    recipes.insert(name.clone(), recipe.clone())
                {
                    ensure!(
                        existing == recipe,
                        "recipe name {name} has conflicting definitions"
                    );
                }
            }
            let files = images
                .iter()
                .map(|entry| {
                    PlannedFile::from_path(
                        relative_to(&workspace, &entry.image.path)?,
                        &entry.image.path,
                    )
                })
                .collect::<anyhow::Result<Vec<_>>>()?;
            groups.push(PlanGroup {
                id: key.id(),
                selected_recipe: recommendation.selected,
                alternative_recipes: recommendation.alternatives,
                review_required: recommendation.review_required,
                reasons: recommendation.reasons,
                metrics,
                representative,
                files,
            });
        }

        Ok(Self {
            version: PLAN_VERSION,
            workspace,
            recipes,
            groups,
        })
    }

    fn read(path: &Path) -> anyhow::Result<Self> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("read plan {}", path.display()))?;
        serde_json::from_str(&raw)
            .with_context(|| format!("parse plan {}", path.display()))
    }

    fn write(&self, path: &Path, replace: bool) -> anyhow::Result<()> {
        ensure!(
            replace || !path.exists(),
            "refusing to replace existing plan {}",
            path.display()
        );
        let parent = path.parent().unwrap_or_else(|| Path::new("."));
        std::fs::create_dir_all(parent)?;
        let mut temporary =
            Builder::new().prefix(".imgo-plan-").tempfile_in(parent)?;
        serde_json::to_writer_pretty(temporary.as_file_mut(), self)?;
        writeln!(temporary.as_file_mut())?;
        temporary.as_file().sync_all()?;
        temporary
            .persist(path)
            .map_err(|error| error.error)
            .with_context(|| format!("commit plan {}", path.display()))?;
        Ok(())
    }

    fn validate(&self) -> anyhow::Result<()> {
        ensure!(
            self.version == PLAN_VERSION,
            "plan version mismatch: expected {PLAN_VERSION}, got {}",
            self.version
        );
        ensure!(
            self.workspace.is_absolute(),
            "plan workspace must be absolute"
        );
        ensure!(
            self.workspace.is_dir(),
            "plan workspace is not a directory"
        );
        ensure!(!self.groups.is_empty(), "plan has no groups");

        let mut group_ids = BTreeSet::new();
        let mut paths = BTreeSet::new();
        for group in &self.groups {
            ensure!(valid_id(&group.id), "invalid group id: {}", group.id);
            ensure!(
                group_ids.insert(&group.id),
                "duplicate group id: {}",
                group.id
            );
            ensure!(
                !group.files.is_empty(),
                "group {} has no files",
                group.id
            );
            ensure!(
                self.recipes.contains_key(&group.selected_recipe),
                "group {} selects unknown recipe {}",
                group.id,
                group.selected_recipe
            );
            ensure!(
                group
                    .files
                    .iter()
                    .any(|file| file.path == group.representative),
                "group {} representative is not a member",
                group.id
            );
            for name in group.recipe_names() {
                ensure!(valid_id(name), "invalid recipe id: {name}");
                let recipe =
                    self.recipes.get(name).with_context(|| {
                        format!(
                            "group {} references unknown recipe {name}",
                            group.id
                        )
                    })?;
                for file in &group.files {
                    validate_relative_path(&file.path)?;
                    let format = ImageFormat::from_path(&file.path)
                        .with_context(|| {
                            format!(
                                "unsupported planned image {}",
                                file.path.display()
                            )
                        })?;
                    let output = recipe.validate_for(format)?;
                    ensure!(
                        matches!(
                            output,
                            ImageFormat::AVIF | ImageFormat::JXL
                        ),
                        "automation recipe {name} must end in AVIF or JXL"
                    );
                }
            }
            for file in &group.files {
                ensure!(
                    paths.insert(&file.path),
                    "image appears in more than one group: {}",
                    file.path.display()
                );
            }
        }
        Ok(())
    }

    fn validate_fingerprints(&self) -> anyhow::Result<()> {
        for group in &self.groups {
            for file in &group.files {
                self.resolve_source(file)?;
            }
        }
        Ok(())
    }

    fn resolve_source(
        &self,
        file: &PlannedFile,
    ) -> anyhow::Result<PathBuf> {
        let source = self.workspace.join(&file.path);
        if file.matches(&source)? {
            return Ok(source);
        }
        let backup = backup_path(&self.workspace, &source);
        if file.matches(&backup)? {
            return Ok(backup);
        }
        bail!(
            "{} changed or disappeared since the plan was generated (backup also does not match)",
            file.path.display()
        )
    }
}

impl PlanGroup {
    fn recipe_names(&self) -> impl Iterator<Item = &String> {
        std::iter::once(&self.selected_recipe)
            .chain(self.alternative_recipes.iter())
    }
}

impl PlannedFile {
    fn from_path(path: PathBuf, absolute: &Path) -> anyhow::Result<Self> {
        let metadata = std::fs::metadata(absolute)?;
        let modified = metadata.modified()?.duration_since(UNIX_EPOCH)?;
        Ok(Self {
            path,
            bytes: metadata.len(),
            modified_unix_seconds: modified.as_secs(),
            modified_subsec_nanos: modified.subsec_nanos(),
        })
    }

    fn matches(&self, path: &Path) -> anyhow::Result<bool> {
        let Ok(metadata) = std::fs::metadata(path) else {
            return Ok(false);
        };
        if !metadata.is_file() || metadata.len() != self.bytes {
            return Ok(false);
        }
        let modified = metadata.modified()?.duration_since(UNIX_EPOCH)?;
        Ok(modified.as_secs() == self.modified_unix_seconds
            && modified.subsec_nanos() == self.modified_subsec_nanos)
    }
}

struct Recommendation {
    selected: String,
    alternatives: Vec<String>,
    review_required: bool,
    reasons: Vec<String>,
    recipes: Vec<(String, Recipe)>,
}

fn recipes_for_group(
    key: GroupKey,
    metrics: GroupMetrics,
) -> Recommendation {
    if key.palette == PaletteClass::Bilevel {
        let name = "jxl-lossless".to_owned();
        return Recommendation {
            selected: name.clone(),
            alternatives: Vec::new(),
            review_required: false,
            reasons: vec![
                "Decoded pixels contain exactly two grayscale levels; no thresholding is needed."
                    .to_owned(),
                "JPEG XL is mathematically lossless and races two modular strategies."
                    .to_owned(),
            ],
            recipes: vec![(name, Recipe::single(Step::Jxl(Jxl::default())))],
        };
    }

    let quality = quality_for(key.scale);
    let safe_name = format!("avif-q{quality}-auto");
    let safe_recipe = avif_recipe(quality, Chroma::Auto, false);
    let compact_quality = quality.saturating_sub(7);
    let compact_chroma = if key.palette == PaletteClass::Color {
        Chroma::Yuv420
    } else {
        Chroma::Auto
    };
    let compact_suffix = if compact_chroma == Chroma::Yuv420 {
        "420"
    } else {
        "auto"
    };
    let compact_name = format!("avif-q{compact_quality}-{compact_suffix}");
    let compact_recipe =
        avif_recipe(compact_quality, compact_chroma, false);
    let mut recommendation = Recommendation {
        selected: safe_name.clone(),
        alternatives: vec![compact_name.clone()],
        review_required: false,
        reasons: vec![format!(
            "Feature group: {:.1}% color, {:.1}% near black/white, entropy {:.2}, fine texture {:.1}% (worst tile {:.1}%).",
            metrics.color_percent,
            metrics.near_bw_percent,
            metrics.gray_entropy,
            metrics.soft_noise_percent,
            metrics.max_tile_soft_noise_percent,
        )],
        recipes: vec![
            (safe_name, safe_recipe),
            (compact_name, compact_recipe),
        ],
    };

    if key.palette == PaletteClass::Color
        && key.texture == TextureClass::Textured
    {
        let grain_name = format!("avif-q{quality}-420-grain");
        recommendation.alternatives.push(grain_name.clone());
        recommendation.recipes.push((
            grain_name,
            avif_recipe(quality, Chroma::Yuv420, true),
        ));
        recommendation.review_required = true;
        recommendation.reasons.push(
            "Color texture is dense enough for AOM grain synthesis to be a candidate; it changes texture and requires 1:1 review."
                .to_owned(),
        );
    }

    if key.palette == PaletteClass::Gray {
        if key.texture == TextureClass::Textured {
            let bilateral_name = format!("bilateral-avif-q{quality}");
            let adaptive_name = format!("adaptive-light-avif-q{quality}");
            recommendation
                .alternatives
                .extend([bilateral_name.clone(), adaptive_name.clone()]);
            recommendation.recipes.push((
                bilateral_name,
                Recipe {
                    steps: vec![
                        Step::Denoise(Denoise::default()),
                        Step::Avif(avif_options(
                            quality,
                            Chroma::Auto,
                            false,
                        )),
                    ],
                },
            ));
            recommendation.recipes.push((
                adaptive_name,
                Recipe {
                    steps: vec![
                        Step::Denoise(Denoise {
                            mode: Mode::AdaptiveBlur,
                            strength: Some("1x0.5".to_owned()),
                        }),
                        Step::Avif(avif_options(
                            quality,
                            Chroma::Auto,
                            false,
                        )),
                    ],
                },
            ));
            recommendation.review_required = true;
            recommendation.reasons.push(
                "Fine grayscale variation may be disposable noise or intentional screentone; both denoise candidates remain unselected until reviewed."
                    .to_owned(),
            );
        }
        if metrics.near_bw_percent >= 68.0 {
            let bilevel_name = "clean-scan-55-jxl".to_owned();
            recommendation.alternatives.push(bilevel_name.clone());
            recommendation.recipes.push((
                bilevel_name,
                Recipe {
                    steps: vec![
                        Step::CleanScan(CleanScan::default()),
                        Step::Jxl(Jxl::default()),
                    ],
                },
            ));
            recommendation.review_required = true;
            recommendation.reasons.push(
                "The page is near-bilevel, but clean sharp screentone has the same histogram signature as a degraded scan; thresholding is never selected automatically."
                    .to_owned(),
            );
        }
        if metrics.near_bw_percent < 40.0
            && metrics.gray_entropy >= 5.5
            && metrics.soft_noise_percent >= 8.0
        {
            let despeckle_name = format!("despeckle-avif-q{quality}");
            recommendation.alternatives.push(despeckle_name.clone());
            recommendation.recipes.push((
                despeckle_name,
                Recipe {
                    steps: vec![
                        Step::Denoise(Denoise {
                            mode: Mode::Despeckle,
                            strength: None,
                        }),
                        Step::Avif(avif_options(
                            quality,
                            Chroma::Auto,
                            false,
                        )),
                    ],
                },
            ));
            recommendation.review_required = true;
            recommendation.reasons.push(
                "Broad grayscale texture resembles stylized pencil/speckle; edge-preserving despeckle is offered for review."
                    .to_owned(),
            );
        }
    }

    recommendation.alternatives.sort();
    recommendation.alternatives.dedup();
    recommendation
}

fn avif_recipe(quality: u8, chroma: Chroma, grain: bool) -> Recipe {
    Recipe::single(Step::Avif(avif_options(quality, chroma, grain)))
}

fn avif_options(quality: u8, chroma: Chroma, grain: bool) -> Avif {
    Avif {
        quality,
        chroma,
        grain,
        ..Avif::default()
    }
}

const fn quality_for(scale: ScaleClass) -> u8 {
    match scale {
        // Smaller canvases receive more quality because defects occupy more of
        // the viewed image. Large pages are tuned for a 2k-ish viewing scale.
        ScaleClass::Small => 68,
        ScaleClass::Medium => 65,
        ScaleClass::Large => 55,
    }
}

fn group_metrics(images: &[AnalyzedImage]) -> GroupMetrics {
    let count = f64::from(u32::try_from(images.len()).unwrap_or(u32::MAX));
    let average = |select: fn(ImageFeatures) -> f64| {
        images
            .iter()
            .map(|image| select(image.features))
            .sum::<f64>()
            / count
    };
    GroupMetrics {
        color_percent: average(|features| features.color_percent),
        gray_entropy: average(|features| features.gray_entropy),
        near_bw_percent: average(|features| features.near_bw_percent),
        detail_percent: average(|features| features.detail_percent),
        soft_noise_percent: average(|features| {
            features.soft_noise_percent
        }),
        max_tile_soft_noise_percent: average(|features| {
            features.max_tile_soft_noise_percent
        }),
        min_longest_edge: images
            .iter()
            .map(|image| image.features.longest_edge())
            .min()
            .unwrap_or(0),
        max_longest_edge: images
            .iter()
            .map(|image| image.features.longest_edge())
            .max()
            .unwrap_or(0),
    }
}

fn representative_index(
    images: &[AnalyzedImage],
    metrics: GroupMetrics,
) -> usize {
    images
        .iter()
        .enumerate()
        .min_by(|(_, left), (_, right)| {
            feature_distance(left.features, metrics)
                .total_cmp(&feature_distance(right.features, metrics))
        })
        .map_or(0, |(index, _)| index)
}

fn feature_distance(
    features: ImageFeatures,
    metrics: GroupMetrics,
) -> f64 {
    (features.color_percent - metrics.color_percent).abs() / 100.0
        + (features.near_bw_percent - metrics.near_bw_percent).abs()
            / 100.0
        + (features.gray_entropy - metrics.gray_entropy).abs() / 8.0
        + (features.detail_percent - metrics.detail_percent).abs() / 100.0
        + (features.soft_noise_percent - metrics.soft_noise_percent).abs()
            / 100.0
        + (features.max_tile_soft_noise_percent
            - metrics.max_tile_soft_noise_percent)
            .abs()
            / 100.0
}

fn relative_to(workspace: &Path, path: &Path) -> anyhow::Result<PathBuf> {
    path.strip_prefix(workspace)
        .map(Path::to_path_buf)
        .with_context(|| {
            format!(
                "{} is outside workspace {}",
                path.display(),
                workspace.display()
            )
        })
}

fn validate_relative_path(path: &Path) -> anyhow::Result<()> {
    ensure!(!path.as_os_str().is_empty(), "empty image path");
    ensure!(!path.is_absolute(), "planned image path must be relative");
    ensure!(
        path.components()
            .all(|component| matches!(component, Component::Normal(_))),
        "planned image path contains traversal or special components: {}",
        path.display()
    );
    Ok(())
}

fn valid_id(id: &str) -> bool {
    !id.is_empty()
        && id.bytes().all(|byte| {
            byte.is_ascii_lowercase()
                || byte.is_ascii_digit()
                || byte == b'-'
        })
}

fn default_analysis_jobs() -> NonZeroU64 {
    let available =
        std::thread::available_parallelism().map_or(1, usize::from);
    let selected = u64::try_from(available.clamp(1, 4)).unwrap_or(1);
    #[expect(
        clippy::unwrap_used,
        reason = "selected is clamped to at least one"
    )]
    NonZeroU64::new(selected).unwrap()
}

fn print_plan_summary(plan: &Plan, output: &Path) {
    let image_count: usize =
        plan.groups.iter().map(|group| group.files.len()).sum();
    println!(
        "Plan: {} images in {} feature groups -> {}",
        image_count,
        plan.groups.len(),
        output.display()
    );
    for group in &plan.groups {
        let review = if group.review_required {
            "review required"
        } else {
            "safe direct route"
        };
        println!(
            "  {:28} {:>4} images  {:24}  {review}",
            group.id,
            group.files.len(),
            group.selected_recipe,
        );
        for reason in &group.reasons {
            println!("    {reason}");
        }
    }
    println!("Next: i preview {}", output.display());
}

#[cfg(test)]
#[expect(clippy::panic_in_result_fn, reason = "test assertions")]
#[expect(clippy::unwrap_used, reason = "test verifies a rejected result")]
mod tests {
    use super::*;

    fn metrics(near_bw_percent: f64) -> GroupMetrics {
        GroupMetrics {
            color_percent: 0.0,
            gray_entropy: 4.0,
            near_bw_percent,
            detail_percent: 10.0,
            soft_noise_percent: 4.0,
            max_tile_soft_noise_percent: 12.0,
            min_longest_edge: 4000,
            max_longest_edge: 4000,
        }
    }

    #[test]
    fn destructive_near_bilevel_recipe_is_never_selected() {
        let recommendation = recipes_for_group(
            GroupKey {
                palette: PaletteClass::Gray,
                texture: TextureClass::Quiet,
                scale: ScaleClass::Large,
            },
            metrics(78.0),
        );
        assert_eq!(recommendation.selected, "avif-q55-auto");
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name == "clean-scan-55-jxl")
        );
        assert!(recommendation.review_required);
    }

    #[test]
    fn grain_synthesis_is_an_unselected_color_alternative() {
        let mut color_metrics = metrics(1.0);
        color_metrics.color_percent = 98.0;
        color_metrics.soft_noise_percent = 40.0;
        let recommendation = recipes_for_group(
            GroupKey {
                palette: PaletteClass::Color,
                texture: TextureClass::Textured,
                scale: ScaleClass::Small,
            },
            color_metrics,
        );
        assert_eq!(recommendation.selected, "avif-q68-auto");
        assert!(
            recommendation
                .alternatives
                .iter()
                .any(|name| name.ends_with("-grain"))
        );
    }

    #[test]
    fn fingerprint_numbers_survive_javascript_editors()
    -> anyhow::Result<()> {
        const JS_MAX_SAFE_INTEGER: u64 = 0x001F_FFFF_FFFF_FFFF;

        let directory = tempfile::tempdir()?;
        let path = directory.path().join("image.png");
        std::fs::write(&path, b"pixels")?;
        let fingerprint =
            PlannedFile::from_path(PathBuf::from("image.png"), &path)?;
        assert!(fingerprint.modified_unix_seconds < JS_MAX_SAFE_INTEGER);
        assert!(
            u64::from(fingerprint.modified_subsec_nanos)
                < JS_MAX_SAFE_INTEGER
        );

        let mut value = serde_json::to_value(&fingerprint)?;
        let object = value
            .as_object_mut()
            .context("planned file did not serialize as an object")?;
        assert!(!object.contains_key("modified_unix_ns"));
        object.insert(
            "unexpected".to_owned(),
            serde_json::Value::Bool(true),
        );
        serde_json::from_value::<PlannedFile>(value).unwrap_err();
        Ok(())
    }
}
