[package]
name = "ino_shell-macros"
description = "Private implementation detail of ino_shell crate"
version = "0.3.0-pre.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/matklad/xshell"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
