[package]
name              = "xtask"
version.workspace = true
edition.workspace = true
publish           = false

[dependencies]
clap.workspace                  = true
clap_complete = "4.5.61"
clap_complete_nushell = "4.5.10"
clap_mangen = { features = [ "env" ], version = "0.3.0" }
nh = { path = "../nh" }
roff = "1.0.0"

[lints]
workspace = true
