[package]
name = "ino_tracing"
version = "1.0.0"
description = "Custom tracing_subcriber configuration."
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
tracing-appender = "0.2.5"
tracing-subscriber.workspace = true

[lints]
workspace = true
