[package]
name = "ino_tracing"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
is-terminal = "0"
tracing.workspace = true
tracing-subscriber.workspace = true
