[package]
name = "ino_tracing"
version = "0.1.1"
description = "Custom tracing_subcriber configuration."
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
