[package]
name = "ino_tracing"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
