[package]
name                   = "nh-clean"
description            = "This is an internal component crate of nh"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license = "EUPL-1.2"
publish                = true

[lib]
path = "src/clean.rs"

[dependencies]
clap.workspace       = true
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
humantime = "2.3.0"
inquire = { default-features = false, features = [ "crossterm" ], version = "0.9.1" }
nh-core = { path = "../nh-core" }
nix = { default-features = false, features = [ "fs", "user", "hostname" ], version = "0.31.1" }
regex = "1.12.2"
tracing.workspace    = true
walkdir = "2.5.0"
yansi = "1.0.1"

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
