[package]
name                   = "nh-nixos"
description            = "This is an internal component crate of nh"
version.workspace      = true
publish                = true
edition.workspace      = true
license = "EUPL-1.2"
rust-version.workspace = true

[dependencies]
clap.workspace           = true
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
inquire = { default-features = false, features = [ "crossterm" ], version = "0.9.1" }
jiff = { default-features = false, features = [ "std", "tzdb-zoneinfo" ], version = "0.2.35" }
nh-core = { path = "../nh-core" }
nh-diff = { path = "../nh-diff" }
nh-installable = { path = "../nh-installable" }
nh-remote = { path = "../nh-remote" }
nix = { default-features = false, features = [ "fs", "user", "hostname" ], version = "0.31.1" }
serde_json.workspace     = true
tempfile = "3.23.0"
tracing.workspace        = true

[lints]
workspace = true
