[package]
name                   = "nh-nixos"
description            = "This is an internal component crate of nh"
version.workspace      = true
publish                = true
edition.workspace      = true
license = "EUPL-1.2"
rust-version.workspace = true

[dependencies]
clap.workspace           = true
color-eyre.workspace     = true
inquire.workspace        = true
jiff.workspace           = true
nh-core = { path = "../nh-core" }
nh-diff = { path = "../nh-diff" }
nh-installable = { path = "../nh-installable" }
nh-remote = { path = "../nh-remote" }
nix.workspace            = true
serde_json.workspace     = true
tempfile.workspace       = true
tracing.workspace        = true

[lints]
workspace = true
