[package]
name = "ino_tap"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tap.workspace = true
tracing.workspace = true

[lints]
workspace = true
