name: "CI tests"

on:
    push:
    pull_request:
    workflow_dispatch:


jobs:

    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4

        -   name: Install Rust
            run: |
                rustup toolchain install stable
                rustup default stable

        -   uses: Swatinem/rust-cache@v2

        -   name: Install extra tools
            uses: taiki-e/install-action@v2
            with:
                tool: nextest

        # -   run: |
        #         sudo apt update -y
        #         sudo apt install -y libsdl2-2.0-0 libsdl2-dev

        -   name: Run tests
            run: |
                cargo nextest run --all-features
