name: "CI tests"

on:
    push:
    pull_request:
    workflow_dispatch:

env:
    RUST_BACKTRACE: 1

jobs:

    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v5

        -   name: Install Rust
            run: |
                rustup toolchain install stable
                rustup default stable

        -   uses: Swatinem/rust-cache@v2

        # -   name: Install extra tools
        #     uses: taiki-e/install-action@v2
        #     with:
        #         tool: nextest@0.9.98

        # -   run: |
        #         sudo apt update -y
        #         sudo apt install -y libsdl2-2.0-0 libsdl2-dev

        -   name: Run tests
            run: |
                cargo test --all-features
