[package]
name                   = "nh-remote"
description            = "This is an internal component crate of nh"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license = "EUPL-1.2"
publish                = true

[lib]
path = "src/remote.rs"

[dependencies]
color-eyre = { default-features = false, features = [ "track-caller" ], version = "0.6.5" }
dix = "2.1.0"
inquire = { default-features = false, features = [ "crossterm" ], version = "0.9.1" }
nh-core = { path = "../nh-core" }
nh-installable = { path = "../nh-installable" }
nix-command = { path = "../nix-command" }
secrecy = { features = [ "serde" ], version = "0.10.3" }
shlex = "2.0.1"
signal-hook = "0.4.1"
subprocess = "1.0.3"
tracing.workspace        = true
which = "8.0.0"

[dev-dependencies]
proptest = "1.9.0"

[lints]
workspace = true
